import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { Search, ArrowUpRight } from 'lucide-react';
import { works } from '@/data/works';
import { artistProfiles } from '@/data/artists';
import { SiteButton } from '@/components/site';
import { CollectionWork } from '@/components/account/home';
import space from '@/assets/space.jpg';
export function ArtistDirectory(){return <main className="container-x pb-24 pt-32"><p className="note text-studio-green">the people behind the work</p><h1 className="mb-12 mt-4 text-5xl font-semibold">Artists</h1><div className="grid grid-cols-2 gap-x-6 gap-y-12 lg:grid-cols-4">{artistProfiles.map(a=><Link to="/artists/$slug" params={{slug:a.slug}} key={a.slug}><img src={a.portrait} alt={a.name} className="aspect-[4/5] w-full object-cover"/><h2 className="mt-5 text-lg font-medium">{a.name}</h2><p className="mt-2 text-xs text-muted-foreground">{a.disciplines.join(' · ')}</p><p className="mt-1 text-xs text-muted-foreground">{a.location}</p></Link>)}</div></main>;}
export function PublicSearch(){const [query,setQuery]=useState('');const [tab,setTab]=useState('All');const match=(text:string)=>text.toLowerCase().includes(query.toLowerCase());const filteredWorks=works.filter(w=>match(`${w.title} ${w.artist.name} ${w.themes?.join(' ')}`));const artists=artistProfiles.filter(a=>match(`${a.name} ${a.disciplines.join(' ')}`));const services=artistProfiles.flatMap(a=>(a.services??[]).map((s,i)=>({a,s,i}))).filter(({a,s})=>match(`${s.title} ${a.name}`));return <main className="container-x pb-24 pt-32"><h1 className="text-4xl font-semibold">Find your next connection.</h1><label className="mb-8 mt-10 flex items-center gap-4 border-b border-border"><Search size={22}/><input aria-label="Search artists, works and services" className="h-16 w-full bg-transparent text-xl outline-none" placeholder="Artists, works, services…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div role="tablist" aria-label="Search categories" className="mb-10 flex flex-wrap gap-3">{['All','Works','Artists','Services','Collections'].map(t=><SiteButton key={t} role="tab" aria-selected={tab===t} onClick={()=>setTab(t)} variant={tab===t?'primary':'outline'} className="px-5 py-3 text-xs">{t}</SiteButton>)}</div>{(tab==='All'||tab==='Works')&&<section><h2 className="mb-6 text-xl font-medium">Works</h2><div className="grid grid-cols-2 gap-6 lg:grid-cols-4">{filteredWorks.slice(0,8).map(w=><CollectionWork key={w.id} work={w}/>)}</div>{!filteredWorks.length&&<p className="py-8 text-sm text-muted-foreground">Nothing matches quite yet.</p>}</section>}{(tab==='All'||tab==='Artists')&&<section className="mt-12"><h2 className="mb-6 text-xl font-medium">Artists</h2><div className="grid gap-5 sm:grid-cols-2 lg:grid-cols-4">{artists.map(a=><Link key={a.slug} to="/artists/$slug" params={{slug:a.slug}} className="flex items-center gap-4"><img src={a.portrait} alt="" className="h-16 w-16 rounded-full object-cover"/><div><p className="text-sm font-medium">{a.name}</p><p className="mt-1 text-xs text-muted-foreground">{a.disciplines[0]}</p></div></Link>)}</div></section>}{(tab==='All'||tab==='Services')&&<section className="mt-12"><h2 className="mb-6 text-xl font-medium">Services</h2><div className="divide-y divide-border">{services.map(({a,s,i})=><Link key={`${a.slug}-${i}`} to="/services/$slug" params={{slug:`${a.slug}-${i}`}} className="flex justify-between gap-4 py-5"><div><h3 className="text-lg font-medium">{s.title}</h3><p className="mt-2 text-xs text-muted-foreground">{a.name}</p></div><ArrowUpRight size={20}/></Link>)}</div></section>}{(tab==='All'||tab==='Collections')&&<section className="mt-12"><h2 className="mb-6 text-xl font-medium">Collections</h2>{match('Quiet Places')&&<Link to="/shop/$collection" params={{collection:'quiet-places'}} className="inline-flex items-center gap-3 text-lg">Quiet Places<ArrowUpRight size={18}/></Link>}</section>}</main>;}
export function ArtForSpaces(){return <main><section className="relative mt-24 h-[600px] max-h-[75svh]"><img src={space} alt="Contemporary artwork in an interior" className="absolute inset-0 h-full w-full object-cover"/><div className="absolute inset-0 bg-ink/25"/><div className="container-x relative flex h-full flex-col justify-end pb-12 text-paper"><h1 className="text-5xl font-semibold sm:text-6xl">Art for Spaces</h1><p className="mt-5 max-w-md text-lg">Work that brings a place to life.</p></div></section><section className="container-x grid gap-10 py-20 lg:grid-cols-2"><h2 className="text-4xl font-medium">A considered collection.<br/>A space with a story.</h2><div><p className="max-w-lg text-base leading-relaxed text-muted-foreground">For homes, hospitality and places that bring people together. Discover artists and work with a connection to the space.</p><div className="mt-8 flex flex-wrap gap-4"><SiteButton href="/shop">Explore works<ArrowUpRight size={17}/></SiteButton><SiteButton href="/artists" variant="outline">Meet the artists</SiteButton></div></div></section></main>;}
export function CollectionPage({slug}:{slug:string}){const title=slug.split('-').map(s=>s.charAt(0).toUpperCase()+s.slice(1)).join(' ');const selection=works.filter(w=>w.themes?.some(t=>t.toLowerCase()===title.toLowerCase()));return <main className="container-x pb-24 pt-32"><p className="note text-studio-green">collected with intention</p><h1 className="mb-5 mt-4 text-5xl font-semibold">{title}</h1><p className="mb-12 text-sm text-muted-foreground">Works with a shared story.</p><div className="grid grid-cols-2 gap-7 lg:grid-cols-4">{selection.map(w=><CollectionWork key={w.id} work={w}/>)}</div>{!selection.length&&<p className="py-10 text-sm text-muted-foreground">Nothing matches quite yet.</p>}</main>;}
export function ServiceDetail({slug}:{slug:string}){const index=Number(slug.split('-').at(-1));const artist=artistProfiles.find(a=>slug.startsWith(a.slug));const service=artist?.services?.[index];if(!artist||!service)return <main className="container-x min-h-[70vh] pt-40"><h1 className="text-4xl">Service not found.</h1><SiteButton href="/artists" className="mt-8">Discover artists</SiteButton></main>;return <main className="container-x pb-24 pt-32"><div className="grid gap-12 lg:grid-cols-2"><img src={artist.heroMedia} alt={service.title} className="aspect-[4/5] w-full object-cover"/><section className="py-8"><p className="note text-studio-green">made together</p><h1 className="mt-4 text-4xl font-semibold">{service.title}</h1><Link to="/artists/$slug" params={{slug:artist.slug}} className="mt-5 inline-block text-sm text-muted-foreground">With {artist.name} ↗</Link><p className="mt-8 text-lg leading-relaxed">{service.description}</p><p className="mt-6 text-sm text-muted-foreground">{service.delivery}</p><SiteButton href="/account/projects" className="mt-10">View collaboration preview<ArrowUpRight size={17}/></SiteButton></section></div></main>;}
