import { Link } from '@tanstack/react-router';
import { ArrowUpRight, Image, MessageSquare } from 'lucide-react';
import { SiteButton } from '@/components/site';
import { sharedProjects, sharedConversations, type Project } from '@/data/ecosystem';
export function StatusLabel({ children }: { children: string }) { return <span className="inline-flex w-fit items-center gap-1.5 rounded-full bg-studio-green/8 px-3 py-1.5 text-[11px] font-medium text-studio-green"><span className="h-1 w-1 rounded-full bg-current"/>{children.replaceAll('-', ' ')}</span>; }
export function EmptyState({ title, detail, action = 'Explore the Shop', href = '/shop' }: { title: string; detail?: string; action?: string; href?: string }) { return <div className="border-y border-border py-14"><Image size={26} strokeWidth={1} className="mb-5 text-studio-green"/><h2 className="max-w-xl text-2xl font-medium leading-snug">{title}</h2>{detail && <p className="mt-3 max-w-md text-sm text-muted-foreground">{detail}</p>}<SiteButton href={href} variant="outline" className="mt-7 px-5 py-3">{action}<ArrowUpRight size={15}/></SiteButton></div>; }
export function ProjectSummary({ project, context }: { project: Project; context: 'creator' | 'customer' }) { return <article className="flex flex-col gap-5 border-t border-border py-6 sm:flex-row sm:items-center"><img src={project.image} alt="" className="h-20 w-20 object-cover"/><div className="min-w-0 flex-1"><p className="mb-2 text-[11px] text-muted-foreground">{context === 'creator' ? `For ${project.customerName}` : `With ${project.creatorName}`}</p><h3 className="text-lg font-medium">{project.title}</h3><p className="mt-2 text-xs text-muted-foreground">{project.nextMilestone}</p></div><StatusLabel>{project.status}</StatusLabel>{context === 'creator' ? <Link to="/creator/projects/$id" params={{id:project.id}} search={{artist:"painter"}} className="inline-flex items-center gap-2 text-xs font-medium">View project<ArrowUpRight size={15}/></Link> : <Link to="/account/projects/$id" params={{id:project.id}} className="inline-flex items-center gap-2 text-xs font-medium">Review project<ArrowUpRight size={15}/></Link>}</article>; }
export function ProjectDetail({ id, context }: { id: string; context: 'creator' | 'customer' }) { const p = sharedProjects.find(p=>p.id === id); if (!p) return <EmptyState title="This project isn’t available."/>; return <section><p className="note text-studio-green">a shared creative journey</p><h1 className="mt-4 text-4xl font-semibold">{p.title}</h1><p className="my-5 text-sm text-muted-foreground">{context === 'creator' ? `For ${p.customerName}` : `With ${p.creatorName}`} · Preview project</p><StatusLabel>{p.status}</StatusLabel><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_280px]"><img src={p.image} alt="Project concept" className="max-h-[440px] w-full object-cover"/><div className="border-t border-border pt-6"><p className="eyebrow text-muted-foreground">Next milestone</p><h2 className="mt-4 text-2xl font-medium">{p.nextMilestone}</h2><p className="mt-4 text-sm leading-relaxed text-muted-foreground">{context==='creator'?'Your client is reviewing the concept.':'The concept is ready for you to review.'}</p><Link to="/artists/$slug" params={{slug:p.artistSlug}} className="mt-6 inline-flex items-center gap-2 text-sm">View artist<ArrowUpRight size={14}/></Link></div></div><div className="mt-10"><MessageThread projectId={p.id}/></div></section>; }
export function MessageThread({ projectId = 'hotel-lobby-mural' }: { projectId?: string }) { const thread = sharedConversations.find(c => c.projectId === projectId); return <section className="max-w-3xl border-t border-border py-6"><div className="flex items-center gap-3"><MessageSquare size={18}/><h2 className="text-lg font-medium">Regarding: {thread?.context.title ?? 'Your projects'}</h2></div>{thread ? <div className="mt-7 space-y-6">{thread.messages.map(m=><article key={m.id} className="border-l-2 border-studio-green/20 pl-5"><div className="flex justify-between gap-4 text-xs"><span className="font-medium">{m.author}</span><span className="text-muted-foreground">{m.time}</span></div><p className="mt-3 text-sm leading-relaxed">{m.body}</p></article>)}<p className="text-xs text-muted-foreground">Preview conversation · Messaging is not connected.</p></div> : <p className="mt-6 text-sm text-muted-foreground">No conversations yet.</p>}</section>; }
