import { Link } from '@tanstack/react-router';
import { useState } from 'react';
import { ArrowLeft, ArrowUpRight, Check } from 'lucide-react';
import { SiteButton } from '@/components/site';
import { useEcosystem } from '@/components/ecosystem/context';
import { EmptyState, StatusLabel, ProjectSummary, MessageThread } from '@/components/ecosystem/primitives';
import { CollectionWork } from './home';
import { accountSections } from './shell';
import { works } from '@/data/works';
import { artistProfiles } from '@/data/artists';
import { sharedProjects } from '@/data/ecosystem';
import { useBag } from '@/lib/bag';
export function AccountDestination({section}: {section:string}) { const {user,scenario} = useEcosystem(); const {saved} = useBag(); const [tab,setTab]=useState('Works'); const [notice,setNotice]=useState(false); const [name,setName]=useState(user.displayName); const [updates,setUpdates]=useState(true); const empty=scenario==='new'||scenario==='creator';
 return <section><p className="eyebrow text-muted-foreground">Buying</p><h1 className="mb-10 mt-4 text-4xl font-semibold">{accountSections[section as keyof typeof accountSections]??'Your account'}</h1>
 {section==='collection'&&(empty?<EmptyState title="Your collection starts with the first piece that speaks to you."/>:<><p className="mb-8 text-sm text-muted-foreground">The pieces you’ve made part of your story. · Preview collection</p><div className="grid gap-8 sm:grid-cols-2 xl:grid-cols-3">{works.slice(0,2).map(w=><CollectionWork work={w} acquired key={w.id}/>)}</div></>)}
 {section==='orders'&&(empty?<EmptyState title="Your first order is a new beginning."/>:<article className="flex flex-col gap-6 rounded-lg border border-border p-6 sm:p-8 sm:flex-row sm:items-center"><img src={works[1]?.image} alt="Home Again" className="h-36 w-28 rounded-lg object-cover"/><div className="flex-1"><p className="text-xs text-muted-foreground">Order IAAA–1026 · Preview</p><h2 className="mt-3 text-xl font-medium">Home Again</h2><p className="mt-2 text-sm text-muted-foreground">Mwila Tembo · K9,800</p><p className="mt-3 text-xs text-muted-foreground">Local delivery · Lusaka</p></div><StatusLabel>Preparing</StatusLabel><Link to="/account/orders/$id" params={{id:'preview-home-again'}} className="inline-flex items-center gap-2 text-sm">View order<ArrowUpRight size={17}/></Link></article>)}
 {section==='projects'&&(scenario==='hotel'?<div>{sharedProjects.map(p=><ProjectSummary project={p} context="customer" key={p.id}/>)}</div>:<EmptyState title="No active projects yet." detail="The right creative collaboration starts with a conversation." action="Discover artists" href="/artists"/>)}
 {section==='saved'&&<><div role="tablist" aria-label="Saved categories" className="mb-9 flex flex-wrap gap-2">{['Works','Artists','Services','Collections'].map(t=><SiteButton key={t} role="tab" aria-selected={tab===t} variant={tab===t?'primary':'outline'} onClick={()=>setTab(t)} className="px-5 py-2.5 text-xs">{t}</SiteButton>)}</div>{tab==='Works'?<div className="grid grid-cols-2 gap-6 xl:grid-cols-3">{(saved.length?works.filter(w=>saved.includes(w.slug)):empty?[]:works.slice(4,7)).map(w=><CollectionWork key={w.id} work={w}/>)}</div>:tab==='Artists'&&!empty?<div className="grid grid-cols-2 gap-6 xl:grid-cols-3">{artistProfiles.slice(0,2).map(a=><Link key={a.slug} to="/artists/$slug" params={{slug:a.slug}}><img src={a.portrait} alt={a.name} className="aspect-[4/5] w-full rounded-lg object-cover"/><h2 className="mt-4 text-lg font-medium">{a.name}</h2><p className="mt-1 text-xs text-muted-foreground">{a.disciplines.join(' · ')}</p></Link>)}</div>:<EmptyState title={`No saved ${tab.toLowerCase()} yet.`}/>}</>}
 {section==='messages'&&(scenario==='hotel'?<MessageThread/>:<EmptyState title="A conversation starts with something that speaks to you." action="Discover artists" href="/artists"/>)}
 {section==='profile'&&<div className="max-w-2xl"><div className="flex flex-wrap items-center justify-between gap-4 border-y border-border py-6"><div><h2 className="text-lg font-medium">{user.displayName}</h2><p className="mt-2 text-xs text-muted-foreground">One account · {user.roles.includes('creator')?'Buying & creating':'Buying'}</p></div><Link to={user.roles.includes('creator')?'/creator':'/join'} search={user.roles.includes('creator')?{artist:'painter'}:{}} className="inline-flex items-center gap-2 text-sm">{user.roles.includes('creator')?'Switch to Creating':'Join as Artist'}<ArrowUpRight size={17}/></Link></div><nav className="mt-8 space-y-1">{['orders','messages','settings'].map(id=><Link key={id} to="/account/$section" params={{section:id}} className="flex justify-between border-b border-border py-5 text-sm">{accountSections[id as keyof typeof accountSections]}<ArrowUpRight size={17}/></Link>)}</nav></div>}
 {section==='settings'&&<form className="max-w-xl space-y-8" onSubmit={e=>{e.preventDefault();setNotice(true)}}><label className="block text-sm font-medium">Display name<input value={name} onChange={e=>{setName(e.target.value);setNotice(false)}} className="mt-3 h-12 w-full border-b border-border bg-transparent font-normal outline-none focus:border-foreground"/></label><label className="flex items-center justify-between gap-4 text-sm">Order & project updates<input type="checkbox" checked={updates} onChange={e=>setUpdates(e.target.checked)} className="h-4 w-4 accent-studio-green"/></label><SiteButton type="submit" className="px-6 py-3">Preview changes</SiteButton>{notice&&<p role="status" className="flex items-center gap-2 text-xs text-studio-green"><Check size={16}/>Preview updated. Account changes are not saved.</p>}</form>}
 {!Object.keys(accountSections).includes(section)&&<EmptyState title="This part of your account isn’t available yet."/>}</section>;
}
export function OrderDetail({id}:{id:string}) { const w=works[1]; if(!w||id!=='preview-home-again')return <EmptyState title="This order isn’t available."/>; return <section><Link to="/account/$section" params={{section:'orders'}} className="inline-flex items-center gap-2 text-xs text-muted-foreground"><ArrowLeft size={16}/>Orders</Link><h1 className="mt-7 text-4xl font-semibold">A piece to call your own.</h1><p className="mt-4 text-xs text-muted-foreground">Order IAAA–1026 · Preview order, not a live purchase</p><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_320px]"><img src={w.image} alt={w.title} className="max-h-[560px] w-full rounded-lg object-contain bg-secondary"/><div><StatusLabel>Preparing</StatusLabel><h2 className="mt-6 text-2xl font-medium">{w.title}</h2><p className="mt-2 text-sm text-muted-foreground">{w.artist.name}</p><p className="mt-6 text-lg">K9,800</p><div className="mt-8 border-y border-border py-6"><p className="eyebrow text-muted-foreground">Delivery</p><p className="mt-3 text-sm">Local delivery · Lusaka</p><p className="mt-3 text-xs leading-relaxed text-muted-foreground">Your artist is carefully preparing the work. Delivery details will appear here when it is on its way.</p></div><Link to="/work/$slug" params={{slug:w.slug}} className="mt-6 inline-flex items-center gap-2 text-sm">View work<ArrowUpRight size={17}/></Link></div></div></section>; }
