import { Link } from '@tanstack/react-router';
import { motion, useReducedMotion } from 'framer-motion';
import { ArrowUpRight, ArrowRight, Package, Heart } from 'lucide-react';
import { SiteButton, EASE } from '@/components/site';
import { useEcosystem } from '@/components/ecosystem/context';
import { EmptyState, StatusLabel, ProjectSummary } from '@/components/ecosystem/primitives';
import { works, type Work } from '@/data/works';
import { sharedProjects } from '@/data/ecosystem';
import { useBag } from '@/lib/bag';
export function CollectionWork({work, acquired=false}: {work:Work; acquired?:boolean}) { return <article><Link to="/work/$slug" params={{slug:work.slug}} className="group block"><div className="aspect-[4/5] overflow-hidden rounded-lg bg-secondary"><img src={work.image} alt={work.title} className="h-full w-full object-cover transition-transform duration-500 group-hover:scale-[1.025]"/></div><h3 className="mt-4 text-lg font-medium">{work.title}</h3></Link><Link to="/artists/$slug" params={{slug:work.artist.slug}} className="mt-1 inline-block text-xs text-muted-foreground">{work.artist.name}</Link><p className="mt-3 text-[11px] text-muted-foreground">{acquired?'Acquired 9 October 2026 · Preview':work.medium}</p>{acquired&&<p className="mt-1 text-[11px] text-studio-green">{work.type==='original'?'Original · 1 of 1':'Limited edition'}</p>}</article>; }
export function AccountHome(){
 const {user,scenario} = useEcosystem(); const {saved} = useBag(); const reduce=useReducedMotion();
 const collection = scenario==='new'||scenario==='creator'?[]:works.slice(0,2);
 const savedWorks = saved.length?works.filter(w=>saved.includes(w.slug)):scenario==='new'?[]:works.slice(4,7);
 const projects = scenario==='hotel'?sharedProjects:[];
 const inProgress = scenario!=='new'&&scenario!=='creator';
 return <motion.div initial={reduce?false:{opacity:0,y:8}} animate={{opacity:1,y:0}} transition={{duration:.4,ease:EASE}}><div className="mb-10 flex flex-wrap items-start justify-between gap-5"><div><p className="note text-studio-green">a place for what speaks to you</p><h1 className="mt-3 text-[36px] font-semibold leading-tight sm:text-[46px]">Welcome back, {user.displayName.split(' ')[0]}.</h1><p className="mt-3 text-sm text-muted-foreground">Your collection, creative connections and things worth keeping.</p></div><span className="mt-2 rounded-full border border-border px-3 py-1.5 text-[10px] text-muted-foreground">Collector preview · Sample data</span></div>
 {inProgress&&<section aria-label="Current order" className="mb-12 grid grid-cols-[80px_minmax(0,1fr)] gap-x-5 gap-y-4 border-y border-border py-6 sm:flex sm:items-center"><img src={works[1]?.image} alt="Home Again" className="row-span-2 h-24 w-20 shrink-0 rounded-lg object-cover sm:w-24"/><div className="min-w-0 flex-1"><p className="eyebrow text-studio-copper">On its way to becoming yours</p><h2 className="mt-2 text-xl font-medium">Home Again</h2><p className="mt-2 text-xs text-muted-foreground">Mwila Tembo · Your artist is preparing the work.</p></div><StatusLabel>Preparing</StatusLabel><Link to="/account/orders/$id" params={{id:'preview-home-again'}} className="col-start-2 inline-flex items-center gap-2 text-xs font-medium">View order<ArrowRight size={15}/></Link></section>}
 {projects[0]&&<section className="mb-12"><div className="mb-5 flex items-center justify-between gap-3"><h2 className="text-xl font-semibold">Projects requiring attention</h2><Link to="/account/$section" params={{section:'projects'}} className="text-xs text-muted-foreground">All projects ↗</Link></div><ProjectSummary project={projects[0]} context="customer"/></section>}
 <div className="grid gap-12 xl:grid-cols-[minmax(0,1fr)_280px]"><section aria-label="Your collection"><div className="mb-6 flex items-center justify-between gap-4"><h2 className="text-xl font-semibold">Your collection <span className="ml-2 text-sm font-normal text-muted-foreground">{collection.length.toString().padStart(2,'0')}</span></h2><Link to="/account/$section" params={{section:'collection'}} className="inline-flex items-center gap-2 text-xs font-medium">View collection<ArrowUpRight size={14}/></Link></div>{collection.length?<div className="grid grid-cols-2 gap-5 sm:gap-8">{collection.map(work=><CollectionWork key={work.id} work={work} acquired/>)}</div>:<EmptyState title="Your collection starts with the first piece that speaks to you."/>}</section>
 <aside className="xl:border-l xl:border-border xl:pl-8"><h2 className="mb-6 text-xl font-semibold">Saved for later</h2>{savedWorks.length?<div className="space-y-5">{savedWorks.map(w=><Link key={w.id} to="/work/$slug" params={{slug:w.slug}} className="flex items-center gap-4"><img src={w.image} alt={w.title} className="h-16 w-16 shrink-0 rounded-lg object-cover"/><div className="min-w-0"><p className="text-sm font-medium">{w.title}</p><p className="mt-1 text-[11px] text-muted-foreground">{w.artist.name}</p></div></Link>)}<Link to="/account/$section" params={{section:'saved'}} className="inline-flex items-center gap-2 pt-3 text-xs font-medium">All saved works<ArrowUpRight size={14}/></Link></div>:<div className="border-t border-border py-6"><Heart size={21} strokeWidth={1.4}/><p className="mt-4 text-sm text-muted-foreground">Keep the pieces you want to come back to.</p><Link to="/shop" className="mt-4 inline-block text-xs font-medium">Explore the Shop ↗</Link></div>}<div className="mt-10 border-t border-border pt-7"><p className="note text-studio-green">creative too?</p><h3 className="mt-3 text-lg font-medium">There’s room for your work.</h3><Link to={user.roles.includes('creator')?'/creator':'/join'} search={user.roles.includes('creator')?{artist:'painter'}:{}} className="mt-5 inline-flex items-center gap-2 text-xs font-medium">{user.roles.includes('creator')?'Go to your studio':'Join as Artist'}<ArrowUpRight size={14}/></Link></div></aside></div>
 <section className="mt-14 border-t border-border pt-8"><h2 className="text-xl font-semibold">Recent activity</h2>{inProgress?<div className="mt-6 divide-y divide-border"><div className="flex items-center gap-4 py-4"><Package size={18} className="text-studio-copper"/><p className="flex-1 text-sm">Home Again is being prepared by the artist.</p><span className="text-[11px] text-muted-foreground">Today</span></div><div className="flex items-center gap-4 py-4"><Heart size={18} className="text-studio-green"/><p className="flex-1 text-sm">You saved River Memory.</p><span className="text-[11px] text-muted-foreground">Yesterday</span></div></div>:<p className="mt-5 text-sm text-muted-foreground">A new chapter, waiting for its first piece.</p>}</section></motion.div>;
}
