import { type ReactNode } from 'react';
import * as Tabs from '@radix-ui/react-tabs';
import * as Dialog from '@radix-ui/react-dialog';
import { ArrowUpRight, X, Plus, Image, Check } from 'lucide-react';
import { SiteButton, IconButton } from '@/components/site';
import { StudioLink } from './controls';
export function ModuleHeader({eyebrow, title, description, children}: {eyebrow?:string;title:string;description?:string;children?:ReactNode}) {return <div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="mb-3 text-xs font-medium text-studio-green">{eyebrow??'Your creative studio'}</p><h1 className="text-3xl font-semibold leading-tight sm:text-4xl">{title}</h1>{description&&<p className="mt-3 max-w-xl text-sm leading-relaxed text-muted-foreground">{description}</p>}</div><div className="flex flex-wrap items-center gap-2">{children}</div></div>}
export function ProductTabs({items,value,onChange}: {items:string[];value:string;onChange:(v:string)=>void}) {return <Tabs.Root value={value} onValueChange={onChange}><Tabs.List className="mb-6 flex gap-5 overflow-x-auto border-b border-border" aria-label="Workspace views">{items.map(item=><Tabs.Trigger asChild key={item} value={item}><SiteButton variant="outline" className="studio-tab relative shrink-0 border-0 bg-transparent px-0 py-3 text-sm text-muted-foreground hover:bg-transparent">{item}</SiteButton></Tabs.Trigger>)}</Tabs.List></Tabs.Root>}
export function ProductDrawer({open,onClose,title,description,children}: {open:boolean;onClose:()=>void;title:string;description?:string;children:ReactNode}){return <Dialog.Root open={open} onOpenChange={v=>{if(!v)onClose()}}><Dialog.Portal><Dialog.Overlay className="fixed inset-0 z-50 bg-ink/35 backdrop-blur-[2px]"/><Dialog.Content className="studio fixed inset-x-0 bottom-0 z-50 max-h-[92svh] overflow-y-auto rounded-t-lg bg-studio-surface p-6 outline-none sm:inset-x-auto sm:bottom-auto sm:left-1/2 sm:top-1/2 sm:w-[min(560px,calc(100vw-3rem))] sm:-translate-x-1/2 sm:-translate-y-1/2 sm:max-h-[86svh] sm:rounded-lg sm:p-8 sm:shadow-2xl"><Dialog.Title className="pr-10 text-2xl font-semibold">{title}</Dialog.Title><Dialog.Description className={description?'mt-3 text-sm leading-relaxed text-muted-foreground':'sr-only'}>{description??'Manage your creative workspace preview.'}</Dialog.Description><Dialog.Close asChild><IconButton ariaLabel="Close drawer" className="absolute right-4 top-5 border-0"><X size={20}/></IconButton></Dialog.Close><div className="mt-8">{children}</div></Dialog.Content></Dialog.Portal></Dialog.Root>}
export function ProductStatus({children}: {children:string}) {const active=['Published','Completed','Confirmed','Available'].includes(children);const warm=['Review','Reserved','Pending','Preparing','New'].includes(children);return <span className={`inline-flex w-fit items-center gap-1.5 rounded-full px-2.5 py-1 text-[12px] font-medium ${active?'bg-background text-studio-green shadow-sm':warm?'bg-background text-studio-copper shadow-sm':'bg-background text-muted-foreground shadow-sm'}`}><span className="h-1 w-1 rounded-full bg-current"/>{children}</span>}
export function ProductEmpty({title,description,section='portfolio',action='Add your first project'}:{title:string;description:string;section?:string;action?:string}) {return <div className="studio-panel relative overflow-hidden p-8 sm:p-12"><div aria-hidden className="studio-pattern absolute right-0 top-0 h-full w-28 opacity-[.04]"/><span className="mb-6 grid h-14 w-14 place-items-center rounded-lg bg-studio-green/6 text-studio-green"><Image size={26} strokeWidth={1.3}/></span><h2 className="max-w-lg text-2xl font-semibold">{title}</h2><p className="mb-6 mt-3 max-w-lg text-sm leading-relaxed text-muted-foreground">{description}</p><StudioLink section={section} className="rounded-full bg-ink px-5 py-3 text-ink-foreground">{action}<Plus size={17}/></StudioLink></div>}
export function PreviewNote(){return <p className="mt-7 text-[13px] text-muted-foreground">Studio preview · Sample records. Changes stay in this preview; no payments or messages are sent.</p>}
export function TrendChart({empty=false}: {empty?:boolean}) {return <div className="relative mt-5 h-36 w-full"><svg viewBox="0 0 640 140" preserveAspectRatio="none" role="img" aria-label={empty?'No profile views yet':'Profile views increased across the last seven days'} className="h-full w-full overflow-visible"><g className="stroke-border" strokeWidth="1">{[20,60,100,139].map(y=><line key={y} x1="0" x2="640" y1={y} y2={y}/>)}</g><path d={empty?'M0 139 L640 139':'M0 110 C30 110 50 90 85 94 S145 114 180 75 S240 85 280 60 S325 90 355 74 S395 110 435 55 S480 65 520 36 S580 50 640 12'} fill="none" className="stroke-studio-green" strokeWidth="2.5" vectorEffect="non-scaling-stroke"/><circle cx="640" cy={empty?'139':'12'} r="4" className="fill-studio-green"/></svg><div className="mt-3 flex justify-between text-[12px] text-muted-foreground">{['Sat','Sun','Mon','Tue','Wed','Thu','Fri'].map(d=><span key={d}>{d}</span>)}</div></div>}
export function ActionButton({children,onClick}: {children:ReactNode;onClick:()=>void}) {return <SiteButton variant="outline" onClick={onClick} className="px-4 py-2.5 text-xs">{children}</SiteButton>}
export function SavedNotice({children='Preview updated.'}:{children?:ReactNode}) {return <p role="status" className="my-4 flex items-start gap-2 text-sm text-studio-success"><Check size={18} className="mt-0.5 shrink-0"/>{children}</p>}
