/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicArtForSpacesRouteImport } from './routes/_public/art-for-spaces'
import { Route as PublicBagRouteImport } from './routes/_public/bag'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountSectionRouteImport } from './routes/account.$section'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminBookingsRouteImport } from './routes/admin.bookings'
import { Route as AdminCollectionsRouteImport } from './routes/admin.collections'
import { Route as AdminCreatorsRouteImport } from './routes/admin.creators'
import { Route as AdminDisputesRouteImport } from './routes/admin.disputes'
import { Route as AdminModerationRouteImport } from './routes/admin.moderation'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPayoutsRouteImport } from './routes/admin.payouts'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSupportRouteImport } from './routes/admin.support'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminVerificationRouteImport } from './routes/admin.verification'
import { Route as AdminWalletsRouteImport } from './routes/admin.wallets'
import { Route as AdminWorksRouteImport } from './routes/admin.works'
import { Route as CheckoutContactRouteImport } from './routes/checkout.contact'
import { Route as CheckoutDeliveryRouteImport } from './routes/checkout.delivery'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout.payment'
import { Route as CheckoutReviewRouteImport } from './routes/checkout.review'
import { Route as CreatorIndexRouteImport } from './routes/creator.index'
import { Route as CreatorSectionRouteImport } from './routes/creator.$section'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSectionRouteImport } from './routes/dashboard.$section'
import { Route as PublicArtistsIndexRouteImport } from './routes/_public/artists.index'
import { Route as PublicArtistsSlugRouteImport } from './routes/_public/artists.$slug'
import { Route as PublicCommissionSlugRouteImport } from './routes/_public/commission.$slug'
import { Route as PublicOrderConfirmedRouteImport } from './routes/_public/order.confirmed'
import { Route as PublicServicesSlugRouteImport } from './routes/_public/services.$slug'
import { Route as PublicShopIndexRouteImport } from './routes/_public/shop.index'
import { Route as PublicShopCollectionRouteImport } from './routes/_public/shop.$collection'
import { Route as PublicWorkSlugRouteImport } from './routes/_public/work.$slug'
import { Route as AccountOrdersIdRouteImport } from './routes/account.orders.$id'
import { Route as AccountProjectsIdRouteImport } from './routes/account.projects.$id'
import { Route as AccountSettingsIndexRouteImport } from './routes/account.settings.index'
import { Route as AccountSettingsPageRouteImport } from './routes/account.settings.$page'
import { Route as AdminBookingsIndexRouteImport } from './routes/admin.bookings.index'
import { Route as AdminCreatorsIndexRouteImport } from './routes/admin.creators.index'
import { Route as AdminCreatorsIdRouteImport } from './routes/admin.creators.$id'
import { Route as AdminDisputesIndexRouteImport } from './routes/admin.disputes.index'
import { Route as AdminDisputesIdRouteImport } from './routes/admin.disputes.$id'
import { Route as AdminModerationIndexRouteImport } from './routes/admin.moderation.index'
import { Route as AdminModerationIdRouteImport } from './routes/admin.moderation.$id'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminPaymentsIndexRouteImport } from './routes/admin.payments.index'
import { Route as AdminPaymentsIdRouteImport } from './routes/admin.payments.$id'
import { Route as AdminPayoutsIndexRouteImport } from './routes/admin.payouts.index'
import { Route as AdminPayoutsIdRouteImport } from './routes/admin.payouts.$id'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin.projects.index'
import { Route as AdminProjectsIdRouteImport } from './routes/admin.projects.$id'
import { Route as AdminRefundsIndexRouteImport } from './routes/admin.refunds.index'
import { Route as AdminRefundsIdRouteImport } from './routes/admin.refunds.$id'
import { Route as AdminServicesIndexRouteImport } from './routes/admin.services.index'
import { Route as AdminSupportIndexRouteImport } from './routes/admin.support.index'
import { Route as AdminSupportIdRouteImport } from './routes/admin.support.$id'
import { Route as AdminUsersIndexRouteImport } from './routes/admin.users.index'
import { Route as AdminUsersIdRouteImport } from './routes/admin.users.$id'
import { Route as AdminVerificationIndexRouteImport } from './routes/admin.verification.index'
import { Route as AdminVerificationIdRouteImport } from './routes/admin.verification.$id'
import { Route as AdminWalletsIndexRouteImport } from './routes/admin.wallets.index'
import { Route as AdminWalletsIdRouteImport } from './routes/admin.wallets.$id'
import { Route as AdminWorksIndexRouteImport } from './routes/admin.works.index'
import { Route as AdminWorksIdRouteImport } from './routes/admin.works.$id'
import { Route as CreatorCommissionsIdRouteImport } from './routes/creator.commissions.$id'
import { Route as CreatorNewKindRouteImport } from './routes/creator.new.$kind'
import { Route as CreatorProjectsIdRouteImport } from './routes/creator.projects.$id'
import { Route as CreatorSettingsIndexRouteImport } from './routes/creator.settings.index'
import { Route as CreatorSettingsPageRouteImport } from './routes/creator.settings.$page'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicArtForSpacesRoute = PublicArtForSpacesRouteImport.update({
  id: '/art-for-spaces',
  path: '/art-for-spaces',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBagRoute = PublicBagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSectionRoute = AccountSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBookingsRoute = AdminBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionsRoute = AdminCollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCreatorsRoute = AdminCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDisputesRoute = AdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => AdminRoute,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPayoutsRoute = AdminPayoutsRouteImport.update({
  id: '/payouts',
  path: '/payouts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/refunds',
  path: '/refunds',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminVerificationRoute = AdminVerificationRouteImport.update({
  id: '/verification',
  path: '/verification',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWalletsRoute = AdminWalletsRouteImport.update({
  id: '/wallets',
  path: '/wallets',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWorksRoute = AdminWorksRouteImport.update({
  id: '/works',
  path: '/works',
  getParentRoute: () => AdminRoute,
} as any)
const CheckoutContactRoute = CheckoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutDeliveryRoute = CheckoutDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutReviewRoute = CheckoutReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CheckoutRoute,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorSectionRoute = CreatorSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => CreatorRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSectionRoute = DashboardSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicArtistsIndexRoute = PublicArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicArtistsSlugRoute = PublicArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicCommissionSlugRoute = PublicCommissionSlugRouteImport.update({
  id: '/commission/$slug',
  path: '/commission/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicOrderConfirmedRoute = PublicOrderConfirmedRouteImport.update({
  id: '/order/confirmed',
  path: '/order/confirmed',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicServicesSlugRoute = PublicServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicShopIndexRoute = PublicShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicShopCollectionRoute = PublicShopCollectionRouteImport.update({
  id: '/shop/$collection',
  path: '/shop/$collection',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicWorkSlugRoute = PublicWorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProjectsIdRoute = AccountProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsIndexRoute = AccountSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSettingsPageRoute = AccountSettingsPageRouteImport.update({
  id: '/settings/$page',
  path: '/settings/$page',
  getParentRoute: () => AccountRoute,
} as any)
const AdminBookingsIndexRoute = AdminBookingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminBookingsRoute,
} as any)
const AdminCreatorsIndexRoute = AdminCreatorsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminCreatorsRoute,
} as any)
const AdminCreatorsIdRoute = AdminCreatorsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCreatorsRoute,
} as any)
const AdminDisputesIndexRoute = AdminDisputesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDisputesRoute,
} as any)
const AdminDisputesIdRoute = AdminDisputesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminDisputesRoute,
} as any)
const AdminModerationIndexRoute = AdminModerationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminModerationRoute,
} as any)
const AdminModerationIdRoute = AdminModerationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminModerationRoute,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminPaymentsIndexRoute = AdminPaymentsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPaymentsRoute,
} as any)
const AdminPaymentsIdRoute = AdminPaymentsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPaymentsRoute,
} as any)
const AdminPayoutsIndexRoute = AdminPayoutsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminPayoutsRoute,
} as any)
const AdminPayoutsIdRoute = AdminPayoutsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminPayoutsRoute,
} as any)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminProjectsIdRoute = AdminProjectsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminProjectsRoute,
} as any)
const AdminRefundsIndexRoute = AdminRefundsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRefundsRoute,
} as any)
const AdminRefundsIdRoute = AdminRefundsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRefundsRoute,
} as any)
const AdminServicesIndexRoute = AdminServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminServicesRoute,
} as any)
const AdminSupportIndexRoute = AdminSupportIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSupportRoute,
} as any)
const AdminSupportIdRoute = AdminSupportIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminSupportRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminUsersIdRoute = AdminUsersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminVerificationIndexRoute = AdminVerificationIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminVerificationRoute,
} as any)
const AdminVerificationIdRoute = AdminVerificationIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminVerificationRoute,
} as any)
const AdminWalletsIndexRoute = AdminWalletsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWalletsRoute,
} as any)
const AdminWalletsIdRoute = AdminWalletsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminWalletsRoute,
} as any)
const AdminWorksIndexRoute = AdminWorksIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminWorksRoute,
} as any)
const AdminWorksIdRoute = AdminWorksIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminWorksRoute,
} as any)
const CreatorCommissionsIdRoute = CreatorCommissionsIdRouteImport.update({
  id: '/commissions/$id',
  path: '/commissions/$id',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorNewKindRoute = CreatorNewKindRouteImport.update({
  id: '/new/$kind',
  path: '/new/$kind',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorProjectsIdRoute = CreatorProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorSettingsIndexRoute = CreatorSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorSettingsPageRoute = CreatorSettingsPageRouteImport.update({
  id: '/settings/$page',
  path: '/settings/$page',
  getParentRoute: () => CreatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/creator': typeof CreatorRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/art-for-spaces': typeof PublicArtForSpacesRoute
  '/bag': typeof PublicBagRoute
  '/search': typeof PublicSearchRoute
  '/account/$section': typeof AccountSectionRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/creators': typeof AdminCreatorsRouteWithChildren
  '/admin/disputes': typeof AdminDisputesRouteWithChildren
  '/admin/moderation': typeof AdminModerationRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRouteWithChildren
  '/admin/payouts': typeof AdminPayoutsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/refunds': typeof AdminRefundsRouteWithChildren
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/verification': typeof AdminVerificationRouteWithChildren
  '/admin/wallets': typeof AdminWalletsRouteWithChildren
  '/admin/works': typeof AdminWorksRouteWithChildren
  '/checkout/contact': typeof CheckoutContactRoute
  '/checkout/delivery': typeof CheckoutDeliveryRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/creator/$section': typeof CreatorSectionRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/artists/$slug': typeof PublicArtistsSlugRoute
  '/commission/$slug': typeof PublicCommissionSlugRoute
  '/order/confirmed': typeof PublicOrderConfirmedRoute
  '/services/$slug': typeof PublicServicesSlugRoute
  '/shop/$collection': typeof PublicShopCollectionRoute
  '/work/$slug': typeof PublicWorkSlugRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/projects/$id': typeof AccountProjectsIdRoute
  '/account/settings/$page': typeof AccountSettingsPageRoute
  '/admin/creators/$id': typeof AdminCreatorsIdRoute
  '/admin/disputes/$id': typeof AdminDisputesIdRoute
  '/admin/moderation/$id': typeof AdminModerationIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/payouts/$id': typeof AdminPayoutsIdRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/refunds/$id': typeof AdminRefundsIdRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/verification/$id': typeof AdminVerificationIdRoute
  '/admin/wallets/$id': typeof AdminWalletsIdRoute
  '/admin/works/$id': typeof AdminWorksIdRoute
  '/creator/commissions/$id': typeof CreatorCommissionsIdRoute
  '/creator/new/$kind': typeof CreatorNewKindRoute
  '/creator/projects/$id': typeof CreatorProjectsIdRoute
  '/creator/settings/$page': typeof CreatorSettingsPageRoute
  '/artists/': typeof PublicArtistsIndexRoute
  '/shop/': typeof PublicShopIndexRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/creators/': typeof AdminCreatorsIndexRoute
  '/admin/disputes/': typeof AdminDisputesIndexRoute
  '/admin/moderation/': typeof AdminModerationIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/payouts/': typeof AdminPayoutsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/refunds/': typeof AdminRefundsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/verification/': typeof AdminVerificationIndexRoute
  '/admin/wallets/': typeof AdminWalletsIndexRoute
  '/admin/works/': typeof AdminWorksIndexRoute
  '/creator/settings/': typeof CreatorSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/art-for-spaces': typeof PublicArtForSpacesRoute
  '/bag': typeof PublicBagRoute
  '/search': typeof PublicSearchRoute
  '/account/$section': typeof AccountSectionRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/checkout/contact': typeof CheckoutContactRoute
  '/checkout/delivery': typeof CheckoutDeliveryRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/creator/$section': typeof CreatorSectionRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/': typeof PublicIndexRoute
  '/account': typeof AccountIndexRoute
  '/admin': typeof AdminIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/artists/$slug': typeof PublicArtistsSlugRoute
  '/commission/$slug': typeof PublicCommissionSlugRoute
  '/order/confirmed': typeof PublicOrderConfirmedRoute
  '/services/$slug': typeof PublicServicesSlugRoute
  '/shop/$collection': typeof PublicShopCollectionRoute
  '/work/$slug': typeof PublicWorkSlugRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/projects/$id': typeof AccountProjectsIdRoute
  '/account/settings/$page': typeof AccountSettingsPageRoute
  '/admin/creators/$id': typeof AdminCreatorsIdRoute
  '/admin/disputes/$id': typeof AdminDisputesIdRoute
  '/admin/moderation/$id': typeof AdminModerationIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/payouts/$id': typeof AdminPayoutsIdRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/refunds/$id': typeof AdminRefundsIdRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/verification/$id': typeof AdminVerificationIdRoute
  '/admin/wallets/$id': typeof AdminWalletsIdRoute
  '/admin/works/$id': typeof AdminWorksIdRoute
  '/creator/commissions/$id': typeof CreatorCommissionsIdRoute
  '/creator/new/$kind': typeof CreatorNewKindRoute
  '/creator/projects/$id': typeof CreatorProjectsIdRoute
  '/creator/settings/$page': typeof CreatorSettingsPageRoute
  '/artists': typeof PublicArtistsIndexRoute
  '/shop': typeof PublicShopIndexRoute
  '/account/settings': typeof AccountSettingsIndexRoute
  '/admin/bookings': typeof AdminBookingsIndexRoute
  '/admin/creators': typeof AdminCreatorsIndexRoute
  '/admin/disputes': typeof AdminDisputesIndexRoute
  '/admin/moderation': typeof AdminModerationIndexRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
  '/admin/payments': typeof AdminPaymentsIndexRoute
  '/admin/payouts': typeof AdminPayoutsIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/refunds': typeof AdminRefundsIndexRoute
  '/admin/services': typeof AdminServicesIndexRoute
  '/admin/support': typeof AdminSupportIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/admin/verification': typeof AdminVerificationIndexRoute
  '/admin/wallets': typeof AdminWalletsIndexRoute
  '/admin/works': typeof AdminWorksIndexRoute
  '/creator/settings': typeof CreatorSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/creator': typeof CreatorRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/signup': typeof SignupRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_public/art-for-spaces': typeof PublicArtForSpacesRoute
  '/_public/bag': typeof PublicBagRoute
  '/_public/search': typeof PublicSearchRoute
  '/account/$section': typeof AccountSectionRoute
  '/account/security': typeof AccountSecurityRoute
  '/admin/bookings': typeof AdminBookingsRouteWithChildren
  '/admin/collections': typeof AdminCollectionsRoute
  '/admin/creators': typeof AdminCreatorsRouteWithChildren
  '/admin/disputes': typeof AdminDisputesRouteWithChildren
  '/admin/moderation': typeof AdminModerationRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRouteWithChildren
  '/admin/payouts': typeof AdminPayoutsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/refunds': typeof AdminRefundsRouteWithChildren
  '/admin/services': typeof AdminServicesRouteWithChildren
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/support': typeof AdminSupportRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/admin/verification': typeof AdminVerificationRouteWithChildren
  '/admin/wallets': typeof AdminWalletsRouteWithChildren
  '/admin/works': typeof AdminWorksRouteWithChildren
  '/checkout/contact': typeof CheckoutContactRoute
  '/checkout/delivery': typeof CheckoutDeliveryRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/creator/$section': typeof CreatorSectionRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/_public/': typeof PublicIndexRoute
  '/account/': typeof AccountIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_public/artists/$slug': typeof PublicArtistsSlugRoute
  '/_public/commission/$slug': typeof PublicCommissionSlugRoute
  '/_public/order/confirmed': typeof PublicOrderConfirmedRoute
  '/_public/services/$slug': typeof PublicServicesSlugRoute
  '/_public/shop/$collection': typeof PublicShopCollectionRoute
  '/_public/work/$slug': typeof PublicWorkSlugRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/projects/$id': typeof AccountProjectsIdRoute
  '/account/settings/$page': typeof AccountSettingsPageRoute
  '/admin/creators/$id': typeof AdminCreatorsIdRoute
  '/admin/disputes/$id': typeof AdminDisputesIdRoute
  '/admin/moderation/$id': typeof AdminModerationIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/payments/$id': typeof AdminPaymentsIdRoute
  '/admin/payouts/$id': typeof AdminPayoutsIdRoute
  '/admin/projects/$id': typeof AdminProjectsIdRoute
  '/admin/refunds/$id': typeof AdminRefundsIdRoute
  '/admin/support/$id': typeof AdminSupportIdRoute
  '/admin/users/$id': typeof AdminUsersIdRoute
  '/admin/verification/$id': typeof AdminVerificationIdRoute
  '/admin/wallets/$id': typeof AdminWalletsIdRoute
  '/admin/works/$id': typeof AdminWorksIdRoute
  '/creator/commissions/$id': typeof CreatorCommissionsIdRoute
  '/creator/new/$kind': typeof CreatorNewKindRoute
  '/creator/projects/$id': typeof CreatorProjectsIdRoute
  '/creator/settings/$page': typeof CreatorSettingsPageRoute
  '/_public/artists/': typeof PublicArtistsIndexRoute
  '/_public/shop/': typeof PublicShopIndexRoute
  '/account/settings/': typeof AccountSettingsIndexRoute
  '/admin/bookings/': typeof AdminBookingsIndexRoute
  '/admin/creators/': typeof AdminCreatorsIndexRoute
  '/admin/disputes/': typeof AdminDisputesIndexRoute
  '/admin/moderation/': typeof AdminModerationIndexRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
  '/admin/payments/': typeof AdminPaymentsIndexRoute
  '/admin/payouts/': typeof AdminPayoutsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/refunds/': typeof AdminRefundsIndexRoute
  '/admin/services/': typeof AdminServicesIndexRoute
  '/admin/support/': typeof AdminSupportIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/admin/verification/': typeof AdminVerificationIndexRoute
  '/admin/wallets/': typeof AdminWalletsIndexRoute
  '/admin/works/': typeof AdminWorksIndexRoute
  '/creator/settings/': typeof CreatorSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/creator'
    | '/dashboard'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/reset-password'
    | '/session-expired'
    | '/signup'
    | '/verify-email'
    | '/art-for-spaces'
    | '/bag'
    | '/search'
    | '/account/$section'
    | '/account/security'
    | '/admin/bookings'
    | '/admin/collections'
    | '/admin/creators'
    | '/admin/disputes'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/projects'
    | '/admin/refunds'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/wallets'
    | '/admin/works'
    | '/checkout/contact'
    | '/checkout/delivery'
    | '/checkout/payment'
    | '/checkout/review'
    | '/creator/$section'
    | '/dashboard/$section'
    | '/account/'
    | '/admin/'
    | '/creator/'
    | '/dashboard/'
    | '/artists/$slug'
    | '/commission/$slug'
    | '/order/confirmed'
    | '/services/$slug'
    | '/shop/$collection'
    | '/work/$slug'
    | '/account/orders/$id'
    | '/account/projects/$id'
    | '/account/settings/$page'
    | '/admin/creators/$id'
    | '/admin/disputes/$id'
    | '/admin/moderation/$id'
    | '/admin/orders/$id'
    | '/admin/payments/$id'
    | '/admin/payouts/$id'
    | '/admin/projects/$id'
    | '/admin/refunds/$id'
    | '/admin/support/$id'
    | '/admin/users/$id'
    | '/admin/verification/$id'
    | '/admin/wallets/$id'
    | '/admin/works/$id'
    | '/creator/commissions/$id'
    | '/creator/new/$kind'
    | '/creator/projects/$id'
    | '/creator/settings/$page'
    | '/artists/'
    | '/shop/'
    | '/account/settings/'
    | '/admin/bookings/'
    | '/admin/creators/'
    | '/admin/disputes/'
    | '/admin/moderation/'
    | '/admin/orders/'
    | '/admin/payments/'
    | '/admin/payouts/'
    | '/admin/projects/'
    | '/admin/refunds/'
    | '/admin/services/'
    | '/admin/support/'
    | '/admin/users/'
    | '/admin/verification/'
    | '/admin/wallets/'
    | '/admin/works/'
    | '/creator/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/checkout'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/reset-password'
    | '/session-expired'
    | '/signup'
    | '/verify-email'
    | '/art-for-spaces'
    | '/bag'
    | '/search'
    | '/account/$section'
    | '/account/security'
    | '/admin/collections'
    | '/admin/notifications'
    | '/admin/settings'
    | '/checkout/contact'
    | '/checkout/delivery'
    | '/checkout/payment'
    | '/checkout/review'
    | '/creator/$section'
    | '/dashboard/$section'
    | '/'
    | '/account'
    | '/admin'
    | '/creator'
    | '/dashboard'
    | '/artists/$slug'
    | '/commission/$slug'
    | '/order/confirmed'
    | '/services/$slug'
    | '/shop/$collection'
    | '/work/$slug'
    | '/account/orders/$id'
    | '/account/projects/$id'
    | '/account/settings/$page'
    | '/admin/creators/$id'
    | '/admin/disputes/$id'
    | '/admin/moderation/$id'
    | '/admin/orders/$id'
    | '/admin/payments/$id'
    | '/admin/payouts/$id'
    | '/admin/projects/$id'
    | '/admin/refunds/$id'
    | '/admin/support/$id'
    | '/admin/users/$id'
    | '/admin/verification/$id'
    | '/admin/wallets/$id'
    | '/admin/works/$id'
    | '/creator/commissions/$id'
    | '/creator/new/$kind'
    | '/creator/projects/$id'
    | '/creator/settings/$page'
    | '/artists'
    | '/shop'
    | '/account/settings'
    | '/admin/bookings'
    | '/admin/creators'
    | '/admin/disputes'
    | '/admin/moderation'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/projects'
    | '/admin/refunds'
    | '/admin/services'
    | '/admin/support'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/wallets'
    | '/admin/works'
    | '/creator/settings'
  id:
    | '__root__'
    | '/_public'
    | '/account'
    | '/admin'
    | '/auth'
    | '/checkout'
    | '/creator'
    | '/dashboard'
    | '/forgot-password'
    | '/join'
    | '/login'
    | '/reset-password'
    | '/session-expired'
    | '/signup'
    | '/verify-email'
    | '/_public/art-for-spaces'
    | '/_public/bag'
    | '/_public/search'
    | '/account/$section'
    | '/account/security'
    | '/admin/bookings'
    | '/admin/collections'
    | '/admin/creators'
    | '/admin/disputes'
    | '/admin/moderation'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/payouts'
    | '/admin/projects'
    | '/admin/refunds'
    | '/admin/services'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/users'
    | '/admin/verification'
    | '/admin/wallets'
    | '/admin/works'
    | '/checkout/contact'
    | '/checkout/delivery'
    | '/checkout/payment'
    | '/checkout/review'
    | '/creator/$section'
    | '/dashboard/$section'
    | '/_public/'
    | '/account/'
    | '/admin/'
    | '/creator/'
    | '/dashboard/'
    | '/_public/artists/$slug'
    | '/_public/commission/$slug'
    | '/_public/order/confirmed'
    | '/_public/services/$slug'
    | '/_public/shop/$collection'
    | '/_public/work/$slug'
    | '/account/orders/$id'
    | '/account/projects/$id'
    | '/account/settings/$page'
    | '/admin/creators/$id'
    | '/admin/disputes/$id'
    | '/admin/moderation/$id'
    | '/admin/orders/$id'
    | '/admin/payments/$id'
    | '/admin/payouts/$id'
    | '/admin/projects/$id'
    | '/admin/refunds/$id'
    | '/admin/support/$id'
    | '/admin/users/$id'
    | '/admin/verification/$id'
    | '/admin/wallets/$id'
    | '/admin/works/$id'
    | '/creator/commissions/$id'
    | '/creator/new/$kind'
    | '/creator/projects/$id'
    | '/creator/settings/$page'
    | '/_public/artists/'
    | '/_public/shop/'
    | '/account/settings/'
    | '/admin/bookings/'
    | '/admin/creators/'
    | '/admin/disputes/'
    | '/admin/moderation/'
    | '/admin/orders/'
    | '/admin/payments/'
    | '/admin/payouts/'
    | '/admin/projects/'
    | '/admin/refunds/'
    | '/admin/services/'
    | '/admin/support/'
    | '/admin/users/'
    | '/admin/verification/'
    | '/admin/wallets/'
    | '/admin/works/'
    | '/creator/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CreatorRoute: typeof CreatorRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  SignupRoute: typeof SignupRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/art-for-spaces': {
      id: '/_public/art-for-spaces'
      path: '/art-for-spaces'
      fullPath: '/art-for-spaces'
      preLoaderRoute: typeof PublicArtForSpacesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/bag': {
      id: '/_public/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof PublicBagRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/$section': {
      id: '/account/$section'
      path: '/$section'
      fullPath: '/account/$section'
      preLoaderRoute: typeof AccountSectionRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bookings': {
      id: '/admin/bookings'
      path: '/bookings'
      fullPath: '/admin/bookings'
      preLoaderRoute: typeof AdminBookingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collections': {
      id: '/admin/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminCollectionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/creators': {
      id: '/admin/creators'
      path: '/creators'
      fullPath: '/admin/creators'
      preLoaderRoute: typeof AdminCreatorsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/disputes': {
      id: '/admin/disputes'
      path: '/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AdminDisputesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payouts': {
      id: '/admin/payouts'
      path: '/payouts'
      fullPath: '/admin/payouts'
      preLoaderRoute: typeof AdminPayoutsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/verification': {
      id: '/admin/verification'
      path: '/verification'
      fullPath: '/admin/verification'
      preLoaderRoute: typeof AdminVerificationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/wallets': {
      id: '/admin/wallets'
      path: '/wallets'
      fullPath: '/admin/wallets'
      preLoaderRoute: typeof AdminWalletsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/works': {
      id: '/admin/works'
      path: '/works'
      fullPath: '/admin/works'
      preLoaderRoute: typeof AdminWorksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/checkout/contact': {
      id: '/checkout/contact'
      path: '/contact'
      fullPath: '/checkout/contact'
      preLoaderRoute: typeof CheckoutContactRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/delivery': {
      id: '/checkout/delivery'
      path: '/delivery'
      fullPath: '/checkout/delivery'
      preLoaderRoute: typeof CheckoutDeliveryRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/review': {
      id: '/checkout/review'
      path: '/review'
      fullPath: '/checkout/review'
      preLoaderRoute: typeof CheckoutReviewRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/$section': {
      id: '/creator/$section'
      path: '/$section'
      fullPath: '/creator/$section'
      preLoaderRoute: typeof CreatorSectionRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$section': {
      id: '/dashboard/$section'
      path: '/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof DashboardSectionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/artists/': {
      id: '/_public/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof PublicArtistsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/artists/$slug': {
      id: '/_public/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof PublicArtistsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/commission/$slug': {
      id: '/_public/commission/$slug'
      path: '/commission/$slug'
      fullPath: '/commission/$slug'
      preLoaderRoute: typeof PublicCommissionSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/order/confirmed': {
      id: '/_public/order/confirmed'
      path: '/order/confirmed'
      fullPath: '/order/confirmed'
      preLoaderRoute: typeof PublicOrderConfirmedRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/services/$slug': {
      id: '/_public/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof PublicServicesSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/shop/': {
      id: '/_public/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof PublicShopIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/shop/$collection': {
      id: '/_public/shop/$collection'
      path: '/shop/$collection'
      fullPath: '/shop/$collection'
      preLoaderRoute: typeof PublicShopCollectionRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/work/$slug': {
      id: '/_public/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof PublicWorkSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/projects/$id': {
      id: '/account/projects/$id'
      path: '/projects/$id'
      fullPath: '/account/projects/$id'
      preLoaderRoute: typeof AccountProjectsIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings/': {
      id: '/account/settings/'
      path: '/settings'
      fullPath: '/account/settings/'
      preLoaderRoute: typeof AccountSettingsIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/settings/$page': {
      id: '/account/settings/$page'
      path: '/settings/$page'
      fullPath: '/account/settings/$page'
      preLoaderRoute: typeof AccountSettingsPageRouteImport
      parentRoute: typeof AccountRoute
    }
    '/admin/bookings/': {
      id: '/admin/bookings/'
      path: '/'
      fullPath: '/admin/bookings/'
      preLoaderRoute: typeof AdminBookingsIndexRouteImport
      parentRoute: typeof AdminBookingsRoute
    }
    '/admin/creators/': {
      id: '/admin/creators/'
      path: '/'
      fullPath: '/admin/creators/'
      preLoaderRoute: typeof AdminCreatorsIndexRouteImport
      parentRoute: typeof AdminCreatorsRoute
    }
    '/admin/creators/$id': {
      id: '/admin/creators/$id'
      path: '/$id'
      fullPath: '/admin/creators/$id'
      preLoaderRoute: typeof AdminCreatorsIdRouteImport
      parentRoute: typeof AdminCreatorsRoute
    }
    '/admin/disputes/': {
      id: '/admin/disputes/'
      path: '/'
      fullPath: '/admin/disputes/'
      preLoaderRoute: typeof AdminDisputesIndexRouteImport
      parentRoute: typeof AdminDisputesRoute
    }
    '/admin/disputes/$id': {
      id: '/admin/disputes/$id'
      path: '/$id'
      fullPath: '/admin/disputes/$id'
      preLoaderRoute: typeof AdminDisputesIdRouteImport
      parentRoute: typeof AdminDisputesRoute
    }
    '/admin/moderation/': {
      id: '/admin/moderation/'
      path: '/'
      fullPath: '/admin/moderation/'
      preLoaderRoute: typeof AdminModerationIndexRouteImport
      parentRoute: typeof AdminModerationRoute
    }
    '/admin/moderation/$id': {
      id: '/admin/moderation/$id'
      path: '/$id'
      fullPath: '/admin/moderation/$id'
      preLoaderRoute: typeof AdminModerationIdRouteImport
      parentRoute: typeof AdminModerationRoute
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/payments/': {
      id: '/admin/payments/'
      path: '/'
      fullPath: '/admin/payments/'
      preLoaderRoute: typeof AdminPaymentsIndexRouteImport
      parentRoute: typeof AdminPaymentsRoute
    }
    '/admin/payments/$id': {
      id: '/admin/payments/$id'
      path: '/$id'
      fullPath: '/admin/payments/$id'
      preLoaderRoute: typeof AdminPaymentsIdRouteImport
      parentRoute: typeof AdminPaymentsRoute
    }
    '/admin/payouts/': {
      id: '/admin/payouts/'
      path: '/'
      fullPath: '/admin/payouts/'
      preLoaderRoute: typeof AdminPayoutsIndexRouteImport
      parentRoute: typeof AdminPayoutsRoute
    }
    '/admin/payouts/$id': {
      id: '/admin/payouts/$id'
      path: '/$id'
      fullPath: '/admin/payouts/$id'
      preLoaderRoute: typeof AdminPayoutsIdRouteImport
      parentRoute: typeof AdminPayoutsRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/projects/$id': {
      id: '/admin/projects/$id'
      path: '/$id'
      fullPath: '/admin/projects/$id'
      preLoaderRoute: typeof AdminProjectsIdRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/refunds/': {
      id: '/admin/refunds/'
      path: '/'
      fullPath: '/admin/refunds/'
      preLoaderRoute: typeof AdminRefundsIndexRouteImport
      parentRoute: typeof AdminRefundsRoute
    }
    '/admin/refunds/$id': {
      id: '/admin/refunds/$id'
      path: '/$id'
      fullPath: '/admin/refunds/$id'
      preLoaderRoute: typeof AdminRefundsIdRouteImport
      parentRoute: typeof AdminRefundsRoute
    }
    '/admin/services/': {
      id: '/admin/services/'
      path: '/'
      fullPath: '/admin/services/'
      preLoaderRoute: typeof AdminServicesIndexRouteImport
      parentRoute: typeof AdminServicesRoute
    }
    '/admin/support/': {
      id: '/admin/support/'
      path: '/'
      fullPath: '/admin/support/'
      preLoaderRoute: typeof AdminSupportIndexRouteImport
      parentRoute: typeof AdminSupportRoute
    }
    '/admin/support/$id': {
      id: '/admin/support/$id'
      path: '/$id'
      fullPath: '/admin/support/$id'
      preLoaderRoute: typeof AdminSupportIdRouteImport
      parentRoute: typeof AdminSupportRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/users/$id': {
      id: '/admin/users/$id'
      path: '/$id'
      fullPath: '/admin/users/$id'
      preLoaderRoute: typeof AdminUsersIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/verification/': {
      id: '/admin/verification/'
      path: '/'
      fullPath: '/admin/verification/'
      preLoaderRoute: typeof AdminVerificationIndexRouteImport
      parentRoute: typeof AdminVerificationRoute
    }
    '/admin/verification/$id': {
      id: '/admin/verification/$id'
      path: '/$id'
      fullPath: '/admin/verification/$id'
      preLoaderRoute: typeof AdminVerificationIdRouteImport
      parentRoute: typeof AdminVerificationRoute
    }
    '/admin/wallets/': {
      id: '/admin/wallets/'
      path: '/'
      fullPath: '/admin/wallets/'
      preLoaderRoute: typeof AdminWalletsIndexRouteImport
      parentRoute: typeof AdminWalletsRoute
    }
    '/admin/wallets/$id': {
      id: '/admin/wallets/$id'
      path: '/$id'
      fullPath: '/admin/wallets/$id'
      preLoaderRoute: typeof AdminWalletsIdRouteImport
      parentRoute: typeof AdminWalletsRoute
    }
    '/admin/works/': {
      id: '/admin/works/'
      path: '/'
      fullPath: '/admin/works/'
      preLoaderRoute: typeof AdminWorksIndexRouteImport
      parentRoute: typeof AdminWorksRoute
    }
    '/admin/works/$id': {
      id: '/admin/works/$id'
      path: '/$id'
      fullPath: '/admin/works/$id'
      preLoaderRoute: typeof AdminWorksIdRouteImport
      parentRoute: typeof AdminWorksRoute
    }
    '/creator/commissions/$id': {
      id: '/creator/commissions/$id'
      path: '/commissions/$id'
      fullPath: '/creator/commissions/$id'
      preLoaderRoute: typeof CreatorCommissionsIdRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/new/$kind': {
      id: '/creator/new/$kind'
      path: '/new/$kind'
      fullPath: '/creator/new/$kind'
      preLoaderRoute: typeof CreatorNewKindRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/projects/$id': {
      id: '/creator/projects/$id'
      path: '/projects/$id'
      fullPath: '/creator/projects/$id'
      preLoaderRoute: typeof CreatorProjectsIdRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/settings/': {
      id: '/creator/settings/'
      path: '/settings'
      fullPath: '/creator/settings/'
      preLoaderRoute: typeof CreatorSettingsIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/settings/$page': {
      id: '/creator/settings/$page'
      path: '/settings/$page'
      fullPath: '/creator/settings/$page'
      preLoaderRoute: typeof CreatorSettingsPageRouteImport
      parentRoute: typeof CreatorRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicArtForSpacesRoute: typeof PublicArtForSpacesRoute
  PublicBagRoute: typeof PublicBagRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicArtistsSlugRoute: typeof PublicArtistsSlugRoute
  PublicCommissionSlugRoute: typeof PublicCommissionSlugRoute
  PublicOrderConfirmedRoute: typeof PublicOrderConfirmedRoute
  PublicServicesSlugRoute: typeof PublicServicesSlugRoute
  PublicShopCollectionRoute: typeof PublicShopCollectionRoute
  PublicWorkSlugRoute: typeof PublicWorkSlugRoute
  PublicArtistsIndexRoute: typeof PublicArtistsIndexRoute
  PublicShopIndexRoute: typeof PublicShopIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicArtForSpacesRoute: PublicArtForSpacesRoute,
  PublicBagRoute: PublicBagRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicArtistsSlugRoute: PublicArtistsSlugRoute,
  PublicCommissionSlugRoute: PublicCommissionSlugRoute,
  PublicOrderConfirmedRoute: PublicOrderConfirmedRoute,
  PublicServicesSlugRoute: PublicServicesSlugRoute,
  PublicShopCollectionRoute: PublicShopCollectionRoute,
  PublicWorkSlugRoute: PublicWorkSlugRoute,
  PublicArtistsIndexRoute: PublicArtistsIndexRoute,
  PublicShopIndexRoute: PublicShopIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AccountRouteChildren {
  AccountSectionRoute: typeof AccountSectionRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
  AccountProjectsIdRoute: typeof AccountProjectsIdRoute
  AccountSettingsPageRoute: typeof AccountSettingsPageRoute
  AccountSettingsIndexRoute: typeof AccountSettingsIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountSectionRoute: AccountSectionRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountOrdersIdRoute: AccountOrdersIdRoute,
  AccountProjectsIdRoute: AccountProjectsIdRoute,
  AccountSettingsPageRoute: AccountSettingsPageRoute,
  AccountSettingsIndexRoute: AccountSettingsIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface AdminBookingsRouteChildren {
  AdminBookingsIndexRoute: typeof AdminBookingsIndexRoute
}

const AdminBookingsRouteChildren: AdminBookingsRouteChildren = {
  AdminBookingsIndexRoute: AdminBookingsIndexRoute,
}

const AdminBookingsRouteWithChildren = AdminBookingsRoute._addFileChildren(
  AdminBookingsRouteChildren,
)

interface AdminCreatorsRouteChildren {
  AdminCreatorsIdRoute: typeof AdminCreatorsIdRoute
  AdminCreatorsIndexRoute: typeof AdminCreatorsIndexRoute
}

const AdminCreatorsRouteChildren: AdminCreatorsRouteChildren = {
  AdminCreatorsIdRoute: AdminCreatorsIdRoute,
  AdminCreatorsIndexRoute: AdminCreatorsIndexRoute,
}

const AdminCreatorsRouteWithChildren = AdminCreatorsRoute._addFileChildren(
  AdminCreatorsRouteChildren,
)

interface AdminDisputesRouteChildren {
  AdminDisputesIdRoute: typeof AdminDisputesIdRoute
  AdminDisputesIndexRoute: typeof AdminDisputesIndexRoute
}

const AdminDisputesRouteChildren: AdminDisputesRouteChildren = {
  AdminDisputesIdRoute: AdminDisputesIdRoute,
  AdminDisputesIndexRoute: AdminDisputesIndexRoute,
}

const AdminDisputesRouteWithChildren = AdminDisputesRoute._addFileChildren(
  AdminDisputesRouteChildren,
)

interface AdminModerationRouteChildren {
  AdminModerationIdRoute: typeof AdminModerationIdRoute
  AdminModerationIndexRoute: typeof AdminModerationIndexRoute
}

const AdminModerationRouteChildren: AdminModerationRouteChildren = {
  AdminModerationIdRoute: AdminModerationIdRoute,
  AdminModerationIndexRoute: AdminModerationIndexRoute,
}

const AdminModerationRouteWithChildren = AdminModerationRoute._addFileChildren(
  AdminModerationRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminPaymentsRouteChildren {
  AdminPaymentsIdRoute: typeof AdminPaymentsIdRoute
  AdminPaymentsIndexRoute: typeof AdminPaymentsIndexRoute
}

const AdminPaymentsRouteChildren: AdminPaymentsRouteChildren = {
  AdminPaymentsIdRoute: AdminPaymentsIdRoute,
  AdminPaymentsIndexRoute: AdminPaymentsIndexRoute,
}

const AdminPaymentsRouteWithChildren = AdminPaymentsRoute._addFileChildren(
  AdminPaymentsRouteChildren,
)

interface AdminPayoutsRouteChildren {
  AdminPayoutsIdRoute: typeof AdminPayoutsIdRoute
  AdminPayoutsIndexRoute: typeof AdminPayoutsIndexRoute
}

const AdminPayoutsRouteChildren: AdminPayoutsRouteChildren = {
  AdminPayoutsIdRoute: AdminPayoutsIdRoute,
  AdminPayoutsIndexRoute: AdminPayoutsIndexRoute,
}

const AdminPayoutsRouteWithChildren = AdminPayoutsRoute._addFileChildren(
  AdminPayoutsRouteChildren,
)

interface AdminProjectsRouteChildren {
  AdminProjectsIdRoute: typeof AdminProjectsIdRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
}

const AdminProjectsRouteChildren: AdminProjectsRouteChildren = {
  AdminProjectsIdRoute: AdminProjectsIdRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
}

const AdminProjectsRouteWithChildren = AdminProjectsRoute._addFileChildren(
  AdminProjectsRouteChildren,
)

interface AdminRefundsRouteChildren {
  AdminRefundsIdRoute: typeof AdminRefundsIdRoute
  AdminRefundsIndexRoute: typeof AdminRefundsIndexRoute
}

const AdminRefundsRouteChildren: AdminRefundsRouteChildren = {
  AdminRefundsIdRoute: AdminRefundsIdRoute,
  AdminRefundsIndexRoute: AdminRefundsIndexRoute,
}

const AdminRefundsRouteWithChildren = AdminRefundsRoute._addFileChildren(
  AdminRefundsRouteChildren,
)

interface AdminServicesRouteChildren {
  AdminServicesIndexRoute: typeof AdminServicesIndexRoute
}

const AdminServicesRouteChildren: AdminServicesRouteChildren = {
  AdminServicesIndexRoute: AdminServicesIndexRoute,
}

const AdminServicesRouteWithChildren = AdminServicesRoute._addFileChildren(
  AdminServicesRouteChildren,
)

interface AdminSupportRouteChildren {
  AdminSupportIdRoute: typeof AdminSupportIdRoute
  AdminSupportIndexRoute: typeof AdminSupportIndexRoute
}

const AdminSupportRouteChildren: AdminSupportRouteChildren = {
  AdminSupportIdRoute: AdminSupportIdRoute,
  AdminSupportIndexRoute: AdminSupportIndexRoute,
}

const AdminSupportRouteWithChildren = AdminSupportRoute._addFileChildren(
  AdminSupportRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersIdRoute: typeof AdminUsersIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersIdRoute: AdminUsersIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminVerificationRouteChildren {
  AdminVerificationIdRoute: typeof AdminVerificationIdRoute
  AdminVerificationIndexRoute: typeof AdminVerificationIndexRoute
}

const AdminVerificationRouteChildren: AdminVerificationRouteChildren = {
  AdminVerificationIdRoute: AdminVerificationIdRoute,
  AdminVerificationIndexRoute: AdminVerificationIndexRoute,
}

const AdminVerificationRouteWithChildren =
  AdminVerificationRoute._addFileChildren(AdminVerificationRouteChildren)

interface AdminWalletsRouteChildren {
  AdminWalletsIdRoute: typeof AdminWalletsIdRoute
  AdminWalletsIndexRoute: typeof AdminWalletsIndexRoute
}

const AdminWalletsRouteChildren: AdminWalletsRouteChildren = {
  AdminWalletsIdRoute: AdminWalletsIdRoute,
  AdminWalletsIndexRoute: AdminWalletsIndexRoute,
}

const AdminWalletsRouteWithChildren = AdminWalletsRoute._addFileChildren(
  AdminWalletsRouteChildren,
)

interface AdminWorksRouteChildren {
  AdminWorksIdRoute: typeof AdminWorksIdRoute
  AdminWorksIndexRoute: typeof AdminWorksIndexRoute
}

const AdminWorksRouteChildren: AdminWorksRouteChildren = {
  AdminWorksIdRoute: AdminWorksIdRoute,
  AdminWorksIndexRoute: AdminWorksIndexRoute,
}

const AdminWorksRouteWithChildren = AdminWorksRoute._addFileChildren(
  AdminWorksRouteChildren,
)

interface AdminRouteChildren {
  AdminBookingsRoute: typeof AdminBookingsRouteWithChildren
  AdminCollectionsRoute: typeof AdminCollectionsRoute
  AdminCreatorsRoute: typeof AdminCreatorsRouteWithChildren
  AdminDisputesRoute: typeof AdminDisputesRouteWithChildren
  AdminModerationRoute: typeof AdminModerationRouteWithChildren
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRouteWithChildren
  AdminPayoutsRoute: typeof AdminPayoutsRouteWithChildren
  AdminProjectsRoute: typeof AdminProjectsRouteWithChildren
  AdminRefundsRoute: typeof AdminRefundsRouteWithChildren
  AdminServicesRoute: typeof AdminServicesRouteWithChildren
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSupportRoute: typeof AdminSupportRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminVerificationRoute: typeof AdminVerificationRouteWithChildren
  AdminWalletsRoute: typeof AdminWalletsRouteWithChildren
  AdminWorksRoute: typeof AdminWorksRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminBookingsRoute: AdminBookingsRouteWithChildren,
  AdminCollectionsRoute: AdminCollectionsRoute,
  AdminCreatorsRoute: AdminCreatorsRouteWithChildren,
  AdminDisputesRoute: AdminDisputesRouteWithChildren,
  AdminModerationRoute: AdminModerationRouteWithChildren,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRouteWithChildren,
  AdminPayoutsRoute: AdminPayoutsRouteWithChildren,
  AdminProjectsRoute: AdminProjectsRouteWithChildren,
  AdminRefundsRoute: AdminRefundsRouteWithChildren,
  AdminServicesRoute: AdminServicesRouteWithChildren,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSupportRoute: AdminSupportRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminVerificationRoute: AdminVerificationRouteWithChildren,
  AdminWalletsRoute: AdminWalletsRouteWithChildren,
  AdminWorksRoute: AdminWorksRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface CheckoutRouteChildren {
  CheckoutContactRoute: typeof CheckoutContactRoute
  CheckoutDeliveryRoute: typeof CheckoutDeliveryRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutReviewRoute: typeof CheckoutReviewRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutContactRoute: CheckoutContactRoute,
  CheckoutDeliveryRoute: CheckoutDeliveryRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutReviewRoute: CheckoutReviewRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface CreatorRouteChildren {
  CreatorSectionRoute: typeof CreatorSectionRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
  CreatorCommissionsIdRoute: typeof CreatorCommissionsIdRoute
  CreatorNewKindRoute: typeof CreatorNewKindRoute
  CreatorProjectsIdRoute: typeof CreatorProjectsIdRoute
  CreatorSettingsPageRoute: typeof CreatorSettingsPageRoute
  CreatorSettingsIndexRoute: typeof CreatorSettingsIndexRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorSectionRoute: CreatorSectionRoute,
  CreatorIndexRoute: CreatorIndexRoute,
  CreatorCommissionsIdRoute: CreatorCommissionsIdRoute,
  CreatorNewKindRoute: CreatorNewKindRoute,
  CreatorProjectsIdRoute: CreatorProjectsIdRoute,
  CreatorSettingsPageRoute: CreatorSettingsPageRoute,
  CreatorSettingsIndexRoute: CreatorSettingsIndexRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface DashboardRouteChildren {
  DashboardSectionRoute: typeof DashboardSectionRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSectionRoute: DashboardSectionRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CreatorRoute: CreatorRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  SignupRoute: SignupRoute,
  VerifyEmailRoute: VerifyEmailRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
