/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as JoinRouteImport } from './routes/join'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicBagRouteImport } from './routes/_public/bag'
import { Route as PublicShopRouteImport } from './routes/_public/shop'
import { Route as CheckoutContactRouteImport } from './routes/checkout.contact'
import { Route as CheckoutDeliveryRouteImport } from './routes/checkout.delivery'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout.payment'
import { Route as CheckoutReviewRouteImport } from './routes/checkout.review'
import { Route as CreatorIndexRouteImport } from './routes/creator.index'
import { Route as CreatorSectionRouteImport } from './routes/creator.$section'
import { Route as PublicArtistsSlugRouteImport } from './routes/_public/artists.$slug'
import { Route as PublicOrderConfirmedRouteImport } from './routes/_public/order.confirmed'
import { Route as PublicWorkSlugRouteImport } from './routes/_public/work.$slug'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBagRoute = PublicBagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicShopRoute = PublicShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => PublicRouteRoute,
} as any)
const CheckoutContactRoute = CheckoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutDeliveryRoute = CheckoutDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutReviewRoute = CheckoutReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CheckoutRoute,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorSectionRoute = CreatorSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => CreatorRoute,
} as any)
const PublicArtistsSlugRoute = PublicArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicOrderConfirmedRoute = PublicOrderConfirmedRouteImport.update({
  id: '/order/confirmed',
  path: '/order/confirmed',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicWorkSlugRoute = PublicWorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/creator': typeof CreatorRouteWithChildren
  '/join': typeof JoinRoute
  '/bag': typeof PublicBagRoute
  '/shop': typeof PublicShopRoute
  '/checkout/contact': typeof CheckoutContactRoute
  '/checkout/delivery': typeof CheckoutDeliveryRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/creator/$section': typeof CreatorSectionRoute
  '/creator/': typeof CreatorIndexRoute
  '/artists/$slug': typeof PublicArtistsSlugRoute
  '/order/confirmed': typeof PublicOrderConfirmedRoute
  '/work/$slug': typeof PublicWorkSlugRoute
}
export interface FileRoutesByTo {
  '/checkout': typeof CheckoutRouteWithChildren
  '/join': typeof JoinRoute
  '/bag': typeof PublicBagRoute
  '/shop': typeof PublicShopRoute
  '/checkout/contact': typeof CheckoutContactRoute
  '/checkout/delivery': typeof CheckoutDeliveryRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/creator/$section': typeof CreatorSectionRoute
  '/': typeof PublicIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/artists/$slug': typeof PublicArtistsSlugRoute
  '/order/confirmed': typeof PublicOrderConfirmedRoute
  '/work/$slug': typeof PublicWorkSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/checkout': typeof CheckoutRouteWithChildren
  '/creator': typeof CreatorRouteWithChildren
  '/join': typeof JoinRoute
  '/_public/bag': typeof PublicBagRoute
  '/_public/shop': typeof PublicShopRoute
  '/checkout/contact': typeof CheckoutContactRoute
  '/checkout/delivery': typeof CheckoutDeliveryRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/creator/$section': typeof CreatorSectionRoute
  '/_public/': typeof PublicIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/_public/artists/$slug': typeof PublicArtistsSlugRoute
  '/_public/order/confirmed': typeof PublicOrderConfirmedRoute
  '/_public/work/$slug': typeof PublicWorkSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/creator'
    | '/join'
    | '/bag'
    | '/shop'
    | '/checkout/contact'
    | '/checkout/delivery'
    | '/checkout/payment'
    | '/checkout/review'
    | '/creator/$section'
    | '/creator/'
    | '/artists/$slug'
    | '/order/confirmed'
    | '/work/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/checkout'
    | '/join'
    | '/bag'
    | '/shop'
    | '/checkout/contact'
    | '/checkout/delivery'
    | '/checkout/payment'
    | '/checkout/review'
    | '/creator/$section'
    | '/'
    | '/creator'
    | '/artists/$slug'
    | '/order/confirmed'
    | '/work/$slug'
  id:
    | '__root__'
    | '/_public'
    | '/checkout'
    | '/creator'
    | '/join'
    | '/_public/bag'
    | '/_public/shop'
    | '/checkout/contact'
    | '/checkout/delivery'
    | '/checkout/payment'
    | '/checkout/review'
    | '/creator/$section'
    | '/_public/'
    | '/creator/'
    | '/_public/artists/$slug'
    | '/_public/order/confirmed'
    | '/_public/work/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CreatorRoute: typeof CreatorRouteWithChildren
  JoinRoute: typeof JoinRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/bag': {
      id: '/_public/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof PublicBagRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/shop': {
      id: '/_public/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof PublicShopRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/checkout/contact': {
      id: '/checkout/contact'
      path: '/contact'
      fullPath: '/checkout/contact'
      preLoaderRoute: typeof CheckoutContactRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/delivery': {
      id: '/checkout/delivery'
      path: '/delivery'
      fullPath: '/checkout/delivery'
      preLoaderRoute: typeof CheckoutDeliveryRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/review': {
      id: '/checkout/review'
      path: '/review'
      fullPath: '/checkout/review'
      preLoaderRoute: typeof CheckoutReviewRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/$section': {
      id: '/creator/$section'
      path: '/$section'
      fullPath: '/creator/$section'
      preLoaderRoute: typeof CreatorSectionRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/_public/artists/$slug': {
      id: '/_public/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof PublicArtistsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/order/confirmed': {
      id: '/_public/order/confirmed'
      path: '/order/confirmed'
      fullPath: '/order/confirmed'
      preLoaderRoute: typeof PublicOrderConfirmedRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/work/$slug': {
      id: '/_public/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof PublicWorkSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicBagRoute: typeof PublicBagRoute
  PublicShopRoute: typeof PublicShopRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicArtistsSlugRoute: typeof PublicArtistsSlugRoute
  PublicOrderConfirmedRoute: typeof PublicOrderConfirmedRoute
  PublicWorkSlugRoute: typeof PublicWorkSlugRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicBagRoute: PublicBagRoute,
  PublicShopRoute: PublicShopRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicArtistsSlugRoute: PublicArtistsSlugRoute,
  PublicOrderConfirmedRoute: PublicOrderConfirmedRoute,
  PublicWorkSlugRoute: PublicWorkSlugRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface CheckoutRouteChildren {
  CheckoutContactRoute: typeof CheckoutContactRoute
  CheckoutDeliveryRoute: typeof CheckoutDeliveryRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutReviewRoute: typeof CheckoutReviewRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutContactRoute: CheckoutContactRoute,
  CheckoutDeliveryRoute: CheckoutDeliveryRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutReviewRoute: CheckoutReviewRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface CreatorRouteChildren {
  CreatorSectionRoute: typeof CreatorSectionRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorSectionRoute: CreatorSectionRoute,
  CreatorIndexRoute: CreatorIndexRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  CheckoutRoute: CheckoutRouteWithChildren,
  CreatorRoute: CreatorRouteWithChildren,
  JoinRoute: JoinRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
