/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteRouteImport } from './routes/_public/route'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as PublicArtForSpacesRouteImport } from './routes/_public/art-for-spaces'
import { Route as PublicBagRouteImport } from './routes/_public/bag'
import { Route as PublicSearchRouteImport } from './routes/_public/search'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as AccountSectionRouteImport } from './routes/account.$section'
import { Route as CheckoutContactRouteImport } from './routes/checkout.contact'
import { Route as CheckoutDeliveryRouteImport } from './routes/checkout.delivery'
import { Route as CheckoutPaymentRouteImport } from './routes/checkout.payment'
import { Route as CheckoutReviewRouteImport } from './routes/checkout.review'
import { Route as CreatorIndexRouteImport } from './routes/creator.index'
import { Route as CreatorSectionRouteImport } from './routes/creator.$section'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as DashboardSectionRouteImport } from './routes/dashboard.$section'
import { Route as PublicArtistsIndexRouteImport } from './routes/_public/artists.index'
import { Route as PublicArtistsSlugRouteImport } from './routes/_public/artists.$slug'
import { Route as PublicOrderConfirmedRouteImport } from './routes/_public/order.confirmed'
import { Route as PublicServicesSlugRouteImport } from './routes/_public/services.$slug'
import { Route as PublicShopIndexRouteImport } from './routes/_public/shop.index'
import { Route as PublicShopCollectionRouteImport } from './routes/_public/shop.$collection'
import { Route as PublicWorkSlugRouteImport } from './routes/_public/work.$slug'
import { Route as AccountOrdersIdRouteImport } from './routes/account.orders.$id'
import { Route as AccountProjectsIdRouteImport } from './routes/account.projects.$id'
import { Route as CreatorNewKindRouteImport } from './routes/creator.new.$kind'
import { Route as CreatorProjectsIdRouteImport } from './routes/creator.projects.$id'

const PublicRouteRoute = PublicRouteRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicArtForSpacesRoute = PublicArtForSpacesRouteImport.update({
  id: '/art-for-spaces',
  path: '/art-for-spaces',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicBagRoute = PublicBagRouteImport.update({
  id: '/bag',
  path: '/bag',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicSearchRoute = PublicSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const AccountSectionRoute = AccountSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AccountRoute,
} as any)
const CheckoutContactRoute = CheckoutContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutDeliveryRoute = CheckoutDeliveryRouteImport.update({
  id: '/delivery',
  path: '/delivery',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutPaymentRoute = CheckoutPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => CheckoutRoute,
} as any)
const CheckoutReviewRoute = CheckoutReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CheckoutRoute,
} as any)
const CreatorIndexRoute = CreatorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorSectionRoute = CreatorSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => CreatorRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSectionRoute = DashboardSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => DashboardRoute,
} as any)
const PublicArtistsIndexRoute = PublicArtistsIndexRouteImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicArtistsSlugRoute = PublicArtistsSlugRouteImport.update({
  id: '/artists/$slug',
  path: '/artists/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicOrderConfirmedRoute = PublicOrderConfirmedRouteImport.update({
  id: '/order/confirmed',
  path: '/order/confirmed',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicServicesSlugRoute = PublicServicesSlugRouteImport.update({
  id: '/services/$slug',
  path: '/services/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicShopIndexRoute = PublicShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicShopCollectionRoute = PublicShopCollectionRouteImport.update({
  id: '/shop/$collection',
  path: '/shop/$collection',
  getParentRoute: () => PublicRouteRoute,
} as any)
const PublicWorkSlugRoute = PublicWorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => PublicRouteRoute,
} as any)
const AccountOrdersIdRoute = AccountOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AccountRoute,
} as any)
const AccountProjectsIdRoute = AccountProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => AccountRoute,
} as any)
const CreatorNewKindRoute = CreatorNewKindRouteImport.update({
  id: '/new/$kind',
  path: '/new/$kind',
  getParentRoute: () => CreatorRoute,
} as any)
const CreatorProjectsIdRoute = CreatorProjectsIdRouteImport.update({
  id: '/projects/$id',
  path: '/projects/$id',
  getParentRoute: () => CreatorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/creator': typeof CreatorRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/art-for-spaces': typeof PublicArtForSpacesRoute
  '/bag': typeof PublicBagRoute
  '/search': typeof PublicSearchRoute
  '/account/$section': typeof AccountSectionRoute
  '/checkout/contact': typeof CheckoutContactRoute
  '/checkout/delivery': typeof CheckoutDeliveryRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/creator/$section': typeof CreatorSectionRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/account/': typeof AccountIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/artists/$slug': typeof PublicArtistsSlugRoute
  '/order/confirmed': typeof PublicOrderConfirmedRoute
  '/services/$slug': typeof PublicServicesSlugRoute
  '/shop/$collection': typeof PublicShopCollectionRoute
  '/work/$slug': typeof PublicWorkSlugRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/projects/$id': typeof AccountProjectsIdRoute
  '/creator/new/$kind': typeof CreatorNewKindRoute
  '/creator/projects/$id': typeof CreatorProjectsIdRoute
  '/artists/': typeof PublicArtistsIndexRoute
  '/shop/': typeof PublicShopIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/art-for-spaces': typeof PublicArtForSpacesRoute
  '/bag': typeof PublicBagRoute
  '/search': typeof PublicSearchRoute
  '/account/$section': typeof AccountSectionRoute
  '/checkout/contact': typeof CheckoutContactRoute
  '/checkout/delivery': typeof CheckoutDeliveryRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/creator/$section': typeof CreatorSectionRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/': typeof PublicIndexRoute
  '/account': typeof AccountIndexRoute
  '/creator': typeof CreatorIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/artists/$slug': typeof PublicArtistsSlugRoute
  '/order/confirmed': typeof PublicOrderConfirmedRoute
  '/services/$slug': typeof PublicServicesSlugRoute
  '/shop/$collection': typeof PublicShopCollectionRoute
  '/work/$slug': typeof PublicWorkSlugRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/projects/$id': typeof AccountProjectsIdRoute
  '/creator/new/$kind': typeof CreatorNewKindRoute
  '/creator/projects/$id': typeof CreatorProjectsIdRoute
  '/artists': typeof PublicArtistsIndexRoute
  '/shop': typeof PublicShopIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteRouteWithChildren
  '/account': typeof AccountRouteWithChildren
  '/auth': typeof AuthRoute
  '/checkout': typeof CheckoutRouteWithChildren
  '/creator': typeof CreatorRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/_public/art-for-spaces': typeof PublicArtForSpacesRoute
  '/_public/bag': typeof PublicBagRoute
  '/_public/search': typeof PublicSearchRoute
  '/account/$section': typeof AccountSectionRoute
  '/checkout/contact': typeof CheckoutContactRoute
  '/checkout/delivery': typeof CheckoutDeliveryRoute
  '/checkout/payment': typeof CheckoutPaymentRoute
  '/checkout/review': typeof CheckoutReviewRoute
  '/creator/$section': typeof CreatorSectionRoute
  '/dashboard/$section': typeof DashboardSectionRoute
  '/_public/': typeof PublicIndexRoute
  '/account/': typeof AccountIndexRoute
  '/creator/': typeof CreatorIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_public/artists/$slug': typeof PublicArtistsSlugRoute
  '/_public/order/confirmed': typeof PublicOrderConfirmedRoute
  '/_public/services/$slug': typeof PublicServicesSlugRoute
  '/_public/shop/$collection': typeof PublicShopCollectionRoute
  '/_public/work/$slug': typeof PublicWorkSlugRoute
  '/account/orders/$id': typeof AccountOrdersIdRoute
  '/account/projects/$id': typeof AccountProjectsIdRoute
  '/creator/new/$kind': typeof CreatorNewKindRoute
  '/creator/projects/$id': typeof CreatorProjectsIdRoute
  '/_public/artists/': typeof PublicArtistsIndexRoute
  '/_public/shop/': typeof PublicShopIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/auth'
    | '/checkout'
    | '/creator'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/art-for-spaces'
    | '/bag'
    | '/search'
    | '/account/$section'
    | '/checkout/contact'
    | '/checkout/delivery'
    | '/checkout/payment'
    | '/checkout/review'
    | '/creator/$section'
    | '/dashboard/$section'
    | '/account/'
    | '/creator/'
    | '/dashboard/'
    | '/artists/$slug'
    | '/order/confirmed'
    | '/services/$slug'
    | '/shop/$collection'
    | '/work/$slug'
    | '/account/orders/$id'
    | '/account/projects/$id'
    | '/creator/new/$kind'
    | '/creator/projects/$id'
    | '/artists/'
    | '/shop/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/checkout'
    | '/join'
    | '/login'
    | '/art-for-spaces'
    | '/bag'
    | '/search'
    | '/account/$section'
    | '/checkout/contact'
    | '/checkout/delivery'
    | '/checkout/payment'
    | '/checkout/review'
    | '/creator/$section'
    | '/dashboard/$section'
    | '/'
    | '/account'
    | '/creator'
    | '/dashboard'
    | '/artists/$slug'
    | '/order/confirmed'
    | '/services/$slug'
    | '/shop/$collection'
    | '/work/$slug'
    | '/account/orders/$id'
    | '/account/projects/$id'
    | '/creator/new/$kind'
    | '/creator/projects/$id'
    | '/artists'
    | '/shop'
  id:
    | '__root__'
    | '/_public'
    | '/account'
    | '/auth'
    | '/checkout'
    | '/creator'
    | '/dashboard'
    | '/join'
    | '/login'
    | '/_public/art-for-spaces'
    | '/_public/bag'
    | '/_public/search'
    | '/account/$section'
    | '/checkout/contact'
    | '/checkout/delivery'
    | '/checkout/payment'
    | '/checkout/review'
    | '/creator/$section'
    | '/dashboard/$section'
    | '/_public/'
    | '/account/'
    | '/creator/'
    | '/dashboard/'
    | '/_public/artists/$slug'
    | '/_public/order/confirmed'
    | '/_public/services/$slug'
    | '/_public/shop/$collection'
    | '/_public/work/$slug'
    | '/account/orders/$id'
    | '/account/projects/$id'
    | '/creator/new/$kind'
    | '/creator/projects/$id'
    | '/_public/artists/'
    | '/_public/shop/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRouteRoute: typeof PublicRouteRouteWithChildren
  AccountRoute: typeof AccountRouteWithChildren
  AuthRoute: typeof AuthRoute
  CheckoutRoute: typeof CheckoutRouteWithChildren
  CreatorRoute: typeof CreatorRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/art-for-spaces': {
      id: '/_public/art-for-spaces'
      path: '/art-for-spaces'
      fullPath: '/art-for-spaces'
      preLoaderRoute: typeof PublicArtForSpacesRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/bag': {
      id: '/_public/bag'
      path: '/bag'
      fullPath: '/bag'
      preLoaderRoute: typeof PublicBagRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/search': {
      id: '/_public/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof PublicSearchRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/$section': {
      id: '/account/$section'
      path: '/$section'
      fullPath: '/account/$section'
      preLoaderRoute: typeof AccountSectionRouteImport
      parentRoute: typeof AccountRoute
    }
    '/checkout/contact': {
      id: '/checkout/contact'
      path: '/contact'
      fullPath: '/checkout/contact'
      preLoaderRoute: typeof CheckoutContactRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/delivery': {
      id: '/checkout/delivery'
      path: '/delivery'
      fullPath: '/checkout/delivery'
      preLoaderRoute: typeof CheckoutDeliveryRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/payment': {
      id: '/checkout/payment'
      path: '/payment'
      fullPath: '/checkout/payment'
      preLoaderRoute: typeof CheckoutPaymentRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/checkout/review': {
      id: '/checkout/review'
      path: '/review'
      fullPath: '/checkout/review'
      preLoaderRoute: typeof CheckoutReviewRouteImport
      parentRoute: typeof CheckoutRoute
    }
    '/creator/': {
      id: '/creator/'
      path: '/'
      fullPath: '/creator/'
      preLoaderRoute: typeof CreatorIndexRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/$section': {
      id: '/creator/$section'
      path: '/$section'
      fullPath: '/creator/$section'
      preLoaderRoute: typeof CreatorSectionRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/$section': {
      id: '/dashboard/$section'
      path: '/$section'
      fullPath: '/dashboard/$section'
      preLoaderRoute: typeof DashboardSectionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/_public/artists/': {
      id: '/_public/artists/'
      path: '/artists'
      fullPath: '/artists/'
      preLoaderRoute: typeof PublicArtistsIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/artists/$slug': {
      id: '/_public/artists/$slug'
      path: '/artists/$slug'
      fullPath: '/artists/$slug'
      preLoaderRoute: typeof PublicArtistsSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/order/confirmed': {
      id: '/_public/order/confirmed'
      path: '/order/confirmed'
      fullPath: '/order/confirmed'
      preLoaderRoute: typeof PublicOrderConfirmedRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/services/$slug': {
      id: '/_public/services/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof PublicServicesSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/shop/': {
      id: '/_public/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof PublicShopIndexRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/shop/$collection': {
      id: '/_public/shop/$collection'
      path: '/shop/$collection'
      fullPath: '/shop/$collection'
      preLoaderRoute: typeof PublicShopCollectionRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/_public/work/$slug': {
      id: '/_public/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof PublicWorkSlugRouteImport
      parentRoute: typeof PublicRouteRoute
    }
    '/account/orders/$id': {
      id: '/account/orders/$id'
      path: '/orders/$id'
      fullPath: '/account/orders/$id'
      preLoaderRoute: typeof AccountOrdersIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/projects/$id': {
      id: '/account/projects/$id'
      path: '/projects/$id'
      fullPath: '/account/projects/$id'
      preLoaderRoute: typeof AccountProjectsIdRouteImport
      parentRoute: typeof AccountRoute
    }
    '/creator/new/$kind': {
      id: '/creator/new/$kind'
      path: '/new/$kind'
      fullPath: '/creator/new/$kind'
      preLoaderRoute: typeof CreatorNewKindRouteImport
      parentRoute: typeof CreatorRoute
    }
    '/creator/projects/$id': {
      id: '/creator/projects/$id'
      path: '/projects/$id'
      fullPath: '/creator/projects/$id'
      preLoaderRoute: typeof CreatorProjectsIdRouteImport
      parentRoute: typeof CreatorRoute
    }
  }
}

interface PublicRouteRouteChildren {
  PublicArtForSpacesRoute: typeof PublicArtForSpacesRoute
  PublicBagRoute: typeof PublicBagRoute
  PublicSearchRoute: typeof PublicSearchRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicArtistsSlugRoute: typeof PublicArtistsSlugRoute
  PublicOrderConfirmedRoute: typeof PublicOrderConfirmedRoute
  PublicServicesSlugRoute: typeof PublicServicesSlugRoute
  PublicShopCollectionRoute: typeof PublicShopCollectionRoute
  PublicWorkSlugRoute: typeof PublicWorkSlugRoute
  PublicArtistsIndexRoute: typeof PublicArtistsIndexRoute
  PublicShopIndexRoute: typeof PublicShopIndexRoute
}

const PublicRouteRouteChildren: PublicRouteRouteChildren = {
  PublicArtForSpacesRoute: PublicArtForSpacesRoute,
  PublicBagRoute: PublicBagRoute,
  PublicSearchRoute: PublicSearchRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicArtistsSlugRoute: PublicArtistsSlugRoute,
  PublicOrderConfirmedRoute: PublicOrderConfirmedRoute,
  PublicServicesSlugRoute: PublicServicesSlugRoute,
  PublicShopCollectionRoute: PublicShopCollectionRoute,
  PublicWorkSlugRoute: PublicWorkSlugRoute,
  PublicArtistsIndexRoute: PublicArtistsIndexRoute,
  PublicShopIndexRoute: PublicShopIndexRoute,
}

const PublicRouteRouteWithChildren = PublicRouteRoute._addFileChildren(
  PublicRouteRouteChildren,
)

interface AccountRouteChildren {
  AccountSectionRoute: typeof AccountSectionRoute
  AccountIndexRoute: typeof AccountIndexRoute
  AccountOrdersIdRoute: typeof AccountOrdersIdRoute
  AccountProjectsIdRoute: typeof AccountProjectsIdRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountSectionRoute: AccountSectionRoute,
  AccountIndexRoute: AccountIndexRoute,
  AccountOrdersIdRoute: AccountOrdersIdRoute,
  AccountProjectsIdRoute: AccountProjectsIdRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface CheckoutRouteChildren {
  CheckoutContactRoute: typeof CheckoutContactRoute
  CheckoutDeliveryRoute: typeof CheckoutDeliveryRoute
  CheckoutPaymentRoute: typeof CheckoutPaymentRoute
  CheckoutReviewRoute: typeof CheckoutReviewRoute
}

const CheckoutRouteChildren: CheckoutRouteChildren = {
  CheckoutContactRoute: CheckoutContactRoute,
  CheckoutDeliveryRoute: CheckoutDeliveryRoute,
  CheckoutPaymentRoute: CheckoutPaymentRoute,
  CheckoutReviewRoute: CheckoutReviewRoute,
}

const CheckoutRouteWithChildren = CheckoutRoute._addFileChildren(
  CheckoutRouteChildren,
)

interface CreatorRouteChildren {
  CreatorSectionRoute: typeof CreatorSectionRoute
  CreatorIndexRoute: typeof CreatorIndexRoute
  CreatorNewKindRoute: typeof CreatorNewKindRoute
  CreatorProjectsIdRoute: typeof CreatorProjectsIdRoute
}

const CreatorRouteChildren: CreatorRouteChildren = {
  CreatorSectionRoute: CreatorSectionRoute,
  CreatorIndexRoute: CreatorIndexRoute,
  CreatorNewKindRoute: CreatorNewKindRoute,
  CreatorProjectsIdRoute: CreatorProjectsIdRoute,
}

const CreatorRouteWithChildren =
  CreatorRoute._addFileChildren(CreatorRouteChildren)

interface DashboardRouteChildren {
  DashboardSectionRoute: typeof DashboardSectionRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardSectionRoute: DashboardSectionRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  PublicRouteRoute: PublicRouteRouteWithChildren,
  AccountRoute: AccountRouteWithChildren,
  AuthRoute: AuthRoute,
  CheckoutRoute: CheckoutRouteWithChildren,
  CreatorRoute: CreatorRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
